import { describe, expect, it } from 'vitest';
import {
  clearAuthorship,
  emptyProvenance,
  explainProvenance,
  isAiAuthored,
  markAllReviewed,
  markReviewed,
  needsReview,
  recordAiAuthorship,
  recordFieldAuthorship,
} from '../../src/features/easy-chart/provenance/provenance';

describe('recording authorship', () => {
  // Amber vs blue is the whole point: it directs attention to what the model GUESSED rather than
  // heard. A verified quote is sourced; everything else is honestly inferred.
  it('marks an item with a verified quote as sourced', () => {
    const state = recordAiAuthorship(emptyProvenance(), {
      resourceIds: ['dx-1'],
      sourceText: 'rapid strep antigen was positive',
    });
    expect(state.byResourceId.get('dx-1')).toMatchObject({
      origin: 'sourced',
      sourceText: 'rapid strep antigen was positive',
    });
  });

  it('marks an item with no quote as inferred', () => {
    const state = recordAiAuthorship(emptyProvenance(), { resourceIds: ['em-1'] });
    expect(state.byResourceId.get('em-1')).toMatchObject({ origin: 'inferred' });
    expect(state.byResourceId.get('em-1')?.sourceText).toBeUndefined();
  });

  // A bulk-run auto-pick is a guess even when the action carried a quote: the quote justifies the
  // finding, not the particular catalogue row that was chosen.
  it('marks a low-confidence auto-pick as inferred even when a quote is present', () => {
    const state = recordAiAuthorship(emptyProvenance(), {
      resourceIds: ['ex-1'],
      sourceText: 'throat injected',
      lowConfidence: true,
    });
    expect(state.byResourceId.get('ex-1')?.origin).toBe('inferred');
  });

  it('marks a template-supplied row as a template default', () => {
    const state = recordAiAuthorship(emptyProvenance(), { resourceIds: ['ex-2'], templateName: 'AOM Right' });
    expect(state.byResourceId.get('ex-2')).toMatchObject({ origin: 'template-default', templateName: 'AOM Right' });
  });

  it('carries a guard caution through to the record', () => {
    const state = recordAiAuthorship(emptyProvenance(), {
      resourceIds: ['v-1'],
      caution: 'no unit was stated; read as °F from the value',
    });
    expect(state.byResourceId.get('v-1')?.caution).toMatch(/no unit was stated/);
  });

  it('does not mutate the previous state', () => {
    const before = emptyProvenance();
    recordAiAuthorship(before, { resourceIds: ['a'] });
    expect(before.byResourceId.size).toBe(0);
  });
});

describe('review state', () => {
  const twoItems = recordAiAuthorship(recordAiAuthorship(emptyProvenance(), { resourceIds: ['a'] }), {
    resourceIds: ['b'],
  });

  it('lists everything the provider has not confirmed', () => {
    expect(needsReview(twoItems).sort()).toEqual(['a', 'b']);
  });

  it('confirms one item without changing it', () => {
    const state = markReviewed(twoItems, ['a']);
    expect(needsReview(state)).toEqual(['b']);
    expect(isAiAuthored(state, 'a')).toBe(true);
  });

  it('confirms everything at once', () => {
    expect(needsReview(markAllReviewed(twoItems))).toEqual([]);
  });
});

describe('hand-editing clears the AI mark', () => {
  // The note must reflect who really wrote what; leaving the mark attributes the provider's own
  // words to the assistant.
  it('drops authorship for an item the provider edited', () => {
    const state = recordAiAuthorship(emptyProvenance(), { resourceIds: ['mdm-1'], sourceText: 'the plan is' });
    const after = clearAuthorship(state, ['mdm-1']);
    expect(isAiAuthored(after, 'mdm-1')).toBe(false);
    expect(explainProvenance(after.byResourceId.get('mdm-1'))).toBe('Entered by you.');
  });

  it('drops ids of deleted rows so the map does not go stale', () => {
    const state = recordAiAuthorship(emptyProvenance(), { resourceIds: ['a', 'b'] });
    expect([...clearAuthorship(state, ['a']).byResourceId.keys()]).toEqual(['b']);
  });
});

describe('per-field provenance for composite items', () => {
  // The procedure itself was dictated, but its field values came from a template default. Tracking
  // only the item would claim the provider stated them.
  it('tracks the item and its fields separately', () => {
    let state = recordAiAuthorship(emptyProvenance(), { resourceIds: ['proc-1'], sourceText: 'closed with sutures' });
    state = recordFieldAuthorship(state, 'proc-1', {
      technique: { origin: 'template-default', templateName: 'Laceration repair' },
    });
    const record = state.byResourceId.get('proc-1');
    expect(record?.origin).toBe('sourced');
    expect(record?.fields?.technique).toMatchObject({ origin: 'template-default' });
  });
});

describe('explainProvenance', () => {
  // This is the answer to "why did you code it that way?" — assembled from stored data, never
  // re-generated by the model, which would produce a plausible reason whether or not it was the real
  // one.
  it('quotes the phrase an item came from', () => {
    expect(explainProvenance({ origin: 'sourced', sourceText: 'temp was one hundred point four' })).toBe(
      'Charted from: “temp was one hundred point four”'
    );
  });

  it('says plainly that an inferred item was not stated', () => {
    expect(explainProvenance({ origin: 'inferred' })).toMatch(/nothing in the visit stated it/);
  });

  it('names the template a default came from', () => {
    expect(explainProvenance({ origin: 'template-default', templateName: 'Croup' })).toMatch(/Croup.*verify/);
  });

  it('appends the review pass reasoning and any caution', () => {
    expect(
      explainProvenance({
        origin: 'review',
        reviewNote: 'The narrative mentions recurrent infections.',
        caution: 'verify the laterality',
      })
    ).toBe('Proposed by the review pass. The narrative mentions recurrent infections. verify the laterality');
  });
});
