// Archetype registry + identity pools for the synthetic population build.
//
// Each archetype points at one of the hand-authored rich scenarios in
// ../examples and annotates it with the patient age band + sex constraint it's
// clinically valid for, plus a relative frequency weight (common UC complaints
// weighted higher than acute/unusual ones). The planner fans these out across
// ~2000 unique patients; the runner clones the referenced JSON and overrides
// the patient identity + visit date/location/staff.
//
// Shared by plan-population.ts and run-population.ts.

export type SexConstraint = 'any' | 'female' | 'male';

export interface Archetype {
  /** Scenario file under ../examples (relative to this dir's parent). */
  file: string;
  /** Short stable key used in the plan. */
  key: string;
  /** Human label for logs. */
  label: string;
  /** Inclusive patient-age band (years) this presentation is plausible for. */
  ageMin: number;
  ageMax: number;
  /** Sex the presentation assumes ('any' = either). */
  sex: SexConstraint;
  /** Relative frequency weight (higher = more common in the population). */
  weight: number;
}

// 46 archetypes spanning infant → elderly, both sexes, common + acute UC cases
// (16 hand-authored + 30 generated gen-*.json scenarios).
// Weights: bread-and-butter complaints (URI, strep, UTI, gastro, sprain,
// laceration, conjunctivitis, rash) high; acute/unusual (MVC, hip fracture,
// delirium, biliary colic, CAP/COPD, asthma flare) low — "typical in most
// cases, some unusual."
export const ARCHETYPES: Archetype[] = [
  { key: 'uri-child', file: 'ethan-kim-uri.json', label: 'URI (child)', ageMin: 3, ageMax: 12, sex: 'any', weight: 11 },
  {
    key: 'strep',
    file: 'sarah-mitchell-strep.json',
    label: 'Strep throat',
    ageMin: 5,
    ageMax: 17,
    sex: 'any',
    weight: 10,
  },
  {
    key: 'sore-throat',
    file: 'jane-doe-urgent-care.json',
    label: 'Sore throat (adult)',
    ageMin: 18,
    ageMax: 45,
    sex: 'any',
    weight: 9,
  },
  {
    key: 'uti-adult-f',
    file: 'priya-patel-uti.json',
    label: 'UTI (adult female)',
    ageMin: 18,
    ageMax: 55,
    sex: 'female',
    weight: 9,
  },
  {
    key: 'gastro-toddler',
    file: 'diego-ramirez-gastroenteritis.json',
    label: 'Gastroenteritis (toddler)',
    ageMin: 1,
    ageMax: 6,
    sex: 'any',
    weight: 8,
  },
  {
    key: 'otitis-infant',
    file: 'maya-carter-otitis.json',
    label: 'Otitis media (infant)',
    ageMin: 0,
    ageMax: 3,
    sex: 'any',
    weight: 8,
  },
  {
    key: 'laceration-child',
    file: 'olivia-bennett-laceration.json',
    label: 'Laceration (child)',
    ageMin: 4,
    ageMax: 14,
    sex: 'any',
    weight: 7,
  },
  {
    key: 'ankle-sprain',
    file: 'aiden-thompson-ankle-sprain.json',
    label: 'Ankle sprain (teen)',
    ageMin: 11,
    ageMax: 30,
    sex: 'any',
    weight: 7,
  },
  {
    key: 'conjunctivitis',
    file: 'linda-foster-conjunctivitis.json',
    label: 'Conjunctivitis',
    ageMin: 5,
    ageMax: 75,
    sex: 'any',
    weight: 7,
  },
  {
    key: 'poison-ivy',
    file: 'rachel-goldstein-poison-ivy.json',
    label: 'Poison ivy / contact dermatitis',
    ageMin: 10,
    ageMax: 60,
    sex: 'any',
    weight: 6,
  },
  {
    key: 'asthma-flare',
    file: 'marcus-williams-asthma.json',
    label: 'Asthma flare',
    ageMin: 14,
    ageMax: 40,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'biliary-colic',
    file: 'james-obrien-biliary-colic.json',
    label: 'Biliary colic',
    ageMin: 30,
    ageMax: 70,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'cap-copd',
    file: 'robert-anderson-cap-copd.json',
    label: 'CAP / COPD exacerbation',
    ageMin: 50,
    ageMax: 88,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'mvc',
    file: 'david-chen-mvc.json',
    label: 'Motor-vehicle collision',
    ageMin: 18,
    ageMax: 70,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'hip-fracture',
    file: 'helen-rivera-hip-fracture.json',
    label: 'Hip fracture (fall, elderly)',
    ageMin: 65,
    ageMax: 92,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'uti-delirium',
    file: 'eleanor-hayes-uti-delirium.json',
    label: 'UTI w/ delirium (elderly)',
    ageMin: 72,
    ageMax: 95,
    sex: 'female',
    weight: 3,
  },
  // ── 30 additional template-less archetypes (variants + new complaints) ──
  // The committed gen-*.json files in ../examples are the source of truth for
  // these scenarios (the one-off generator script has been removed); they carry
  // diagnoses/exam/ROS/MDM/Rx in the scenario (harness Phase 5.5). Available
  // for future plan-population runs.
  {
    key: 'mono',
    file: 'gen-mono.json',
    label: 'Infectious mononucleosis',
    ageMin: 14,
    ageMax: 24,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'bronchitis',
    file: 'gen-bronchitis.json',
    label: 'Acute bronchitis',
    ageMin: 18,
    ageMax: 70,
    sex: 'any',
    weight: 6,
  },
  { key: 'covid', file: 'gen-covid.json', label: 'COVID-19', ageMin: 5, ageMax: 80, sex: 'any', weight: 5 },
  { key: 'influenza', file: 'gen-influenza.json', label: 'Influenza', ageMin: 5, ageMax: 80, sex: 'any', weight: 5 },
  {
    key: 'croup',
    file: 'gen-croup.json',
    label: 'Croup (laryngotracheitis)',
    ageMin: 1,
    ageMax: 5,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'sinusitis',
    file: 'gen-sinusitis.json',
    label: 'Acute bacterial sinusitis',
    ageMin: 18,
    ageMax: 70,
    sex: 'any',
    weight: 6,
  },
  {
    key: 'otitis-externa',
    file: 'gen-otitis-externa.json',
    label: 'Otitis externa (swimmer’s ear)',
    ageMin: 5,
    ageMax: 50,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'pyelonephritis',
    file: 'gen-pyelonephritis.json',
    label: 'Acute pyelonephritis',
    ageMin: 18,
    ageMax: 55,
    sex: 'female',
    weight: 4,
  },
  {
    key: 'allergic-conjunctivitis',
    file: 'gen-allergic-conjunctivitis.json',
    label: 'Allergic conjunctivitis',
    ageMin: 5,
    ageMax: 60,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'hand-laceration',
    file: 'gen-hand-laceration.json',
    label: 'Hand laceration (sutured)',
    ageMin: 8,
    ageMax: 60,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'ankle-fracture',
    file: 'gen-ankle-fracture.json',
    label: 'Ankle fracture (lateral malleolus)',
    ageMin: 14,
    ageMax: 60,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'urticaria',
    file: 'gen-urticaria.json',
    label: 'Acute allergic reaction (urticaria)',
    ageMin: 5,
    ageMax: 70,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'migraine',
    file: 'gen-migraine.json',
    label: 'Migraine headache',
    ageMin: 16,
    ageMax: 55,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'back-strain',
    file: 'gen-back-strain.json',
    label: 'Acute lumbar strain',
    ageMin: 20,
    ageMax: 60,
    sex: 'any',
    weight: 6,
  },
  {
    key: 'cellulitis',
    file: 'gen-cellulitis.json',
    label: 'Cellulitis of the leg',
    ageMin: 18,
    ageMax: 75,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'dental-abscess',
    file: 'gen-dental-abscess.json',
    label: 'Dental abscess',
    ageMin: 18,
    ageMax: 65,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'renal-colic',
    file: 'gen-renal-colic.json',
    label: 'Renal colic (kidney stone)',
    ageMin: 25,
    ageMax: 65,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'vertigo-bppv',
    file: 'gen-vertigo-bppv.json',
    label: 'Benign positional vertigo (BPPV)',
    ageMin: 40,
    ageMax: 80,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'wrist-fracture',
    file: 'gen-wrist-fracture.json',
    label: 'Distal radius fracture (FOOSH)',
    ageMin: 8,
    ageMax: 70,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'concussion',
    file: 'gen-concussion.json',
    label: 'Concussion',
    ageMin: 12,
    ageMax: 45,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'dog-bite',
    file: 'gen-dog-bite.json',
    label: 'Dog bite (hand)',
    ageMin: 5,
    ageMax: 70,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'epistaxis',
    file: 'gen-epistaxis.json',
    label: 'Epistaxis (nosebleed)',
    ageMin: 6,
    ageMax: 80,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'minor-burn',
    file: 'gen-minor-burn.json',
    label: 'Second-degree burn (forearm)',
    ageMin: 5,
    ageMax: 65,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'corneal-abrasion',
    file: 'gen-corneal-abrasion.json',
    label: 'Corneal abrasion',
    ageMin: 8,
    ageMax: 60,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'dehydration',
    file: 'gen-dehydration.json',
    label: 'Dehydration',
    ageMin: 2,
    ageMax: 75,
    sex: 'any',
    weight: 4,
  },
  {
    key: 'costochondritis',
    file: 'gen-costochondritis.json',
    label: 'Costochondritis',
    ageMin: 18,
    ageMax: 55,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'cervicitis-sti',
    file: 'gen-cervicitis-sti.json',
    label: 'Dysuria / suspected STI',
    ageMin: 18,
    ageMax: 40,
    sex: 'female',
    weight: 4,
  },
  {
    key: 'contact-dermatitis',
    file: 'gen-contact-dermatitis.json',
    label: 'Contact dermatitis',
    ageMin: 5,
    ageMax: 70,
    sex: 'any',
    weight: 5,
  },
  {
    key: 'plantar-fasciitis',
    file: 'gen-plantar-fasciitis.json',
    label: 'Plantar fasciitis',
    ageMin: 25,
    ageMax: 65,
    sex: 'any',
    weight: 3,
  },
  {
    key: 'impetigo',
    file: 'gen-impetigo.json',
    label: 'Impetigo (pediatric)',
    ageMin: 2,
    ageMax: 12,
    sex: 'any',
    weight: 5,
  },
];

export const ARCHETYPE_BY_KEY: Record<string, Archetype> = Object.fromEntries(ARCHETYPES.map((a) => [a.key, a]));

// Diverse identity pools. Large enough (≈140 first names/sex × ≈320 last names =
// ~45k combos/sex) that the planner can assign every patient a UNIQUE full name
// with last names spread thinly (~6 patients/last name across 2000). Combined
// with DOB variation these yield far more than 2000 unique (name, DOB) keys.
export const FIRST_NAMES_F = [
  'Olivia',
  'Emma',
  'Sophia',
  'Isabella',
  'Mia',
  'Amara',
  'Aaliyah',
  'Zoe',
  'Leila',
  'Priya',
  'Sofia',
  'Camila',
  'Valentina',
  'Mei',
  'Hana',
  'Yuki',
  'Jiwoo',
  'Fatima',
  'Aisha',
  'Nadia',
  'Grace',
  'Chloe',
  'Ava',
  'Layla',
  'Nia',
  'Imani',
  'Destiny',
  'Elena',
  'Lucia',
  'Carmen',
  'Hannah',
  'Ruth',
  'Esther',
  'Margaret',
  'Dorothy',
  'Helen',
  'Rosa',
  'Ingrid',
  'Anya',
  'Keiko',
  'Emily',
  'Abigail',
  'Charlotte',
  'Harper',
  'Evelyn',
  'Amelia',
  'Ella',
  'Scarlett',
  'Lily',
  'Aria',
  'Penelope',
  'Nora',
  'Hazel',
  'Violet',
  'Aurora',
  'Savannah',
  'Audrey',
  'Brooklyn',
  'Bella',
  'Claire',
  'Skylar',
  'Lucy',
  'Paisley',
  'Naomi',
  'Eliana',
  'Quinn',
  'Genesis',
  'Caroline',
  'Kennedy',
  'Maya',
  'Willow',
  'Kinsley',
  'Ruby',
  'Eva',
  'Clara',
  'Vivian',
  'Reagan',
  'Mackenzie',
  'Madeline',
  'Ximena',
  'Gabriela',
  'Daniela',
  'Mariana',
  'Catalina',
  'Renata',
  'Soledad',
  'Pilar',
  'Beatriz',
  'Inés',
  'Lourdes',
  'Yara',
  'Layan',
  'Zaynab',
  'Amina',
  'Salma',
  'Noor',
  'Dalia',
  'Rania',
  'Farah',
  'Leila',
  'Ananya',
  'Aditi',
  'Diya',
  'Ishani',
  'Kavya',
  'Meera',
  'Saanvi',
  'Tara',
  'Nisha',
  'Pooja',
  'Wen',
  'Ling',
  'Xiulan',
  'Fang',
  'Jia',
  'Min',
  'Sora',
  'Yuna',
  'Haru',
  'Sakura',
  'Chiamaka',
  'Ngozi',
  'Adaeze',
  'Folake',
  'Zola',
  'Thandiwe',
  'Ayanna',
  'Jamila',
  'Kenya',
  'Latoya',
  'Freya',
  'Astrid',
  'Sigrid',
  'Katarina',
  'Magda',
  'Liesel',
  'Saoirse',
  'Niamh',
  'Bridget',
  'Colette',
];
export const FIRST_NAMES_M = [
  'Liam',
  'Noah',
  'Ethan',
  'Mateo',
  'Diego',
  'Kai',
  'Andre',
  'Marcus',
  'Malik',
  'Omar',
  'Hassan',
  'Wei',
  'Jin',
  'Hiro',
  'Santiago',
  'Carlos',
  'Javier',
  'Tyrone',
  'Darnell',
  'Samuel',
  'Daniel',
  'James',
  'Benjamin',
  'Lucas',
  'Aiden',
  'Elijah',
  'Isaiah',
  'Amir',
  'Raj',
  'Dmitri',
  'Gabriel',
  'Henry',
  'Walter',
  'Arthur',
  'Frank',
  'Stanley',
  'Reuben',
  'Cyrus',
  'Kofi',
  'Tariq',
  'Oliver',
  'William',
  'Alexander',
  'Michael',
  'Mason',
  'Logan',
  'Jackson',
  'Sebastian',
  'Jack',
  'Owen',
  'Theodore',
  'Levi',
  'Wyatt',
  'Julian',
  'Grayson',
  'Leo',
  'Lincoln',
  'Hudson',
  'Christopher',
  'Joshua',
  'Andrew',
  'Nathan',
  'Ryan',
  'Caleb',
  'Thomas',
  'Charles',
  'Connor',
  'Eli',
  'Aaron',
  'Adrian',
  'Miguel',
  'Alejandro',
  'Emiliano',
  'Tomás',
  'Rafael',
  'Nicolás',
  'Esteban',
  'Andrés',
  'Ignacio',
  'Felipe',
  'Ahmed',
  'Yusuf',
  'Karim',
  'Khalid',
  'Bilal',
  'Zaid',
  'Faisal',
  'Ibrahim',
  'Sami',
  'Rashid',
  'Arjun',
  'Rohan',
  'Aarav',
  'Vikram',
  'Dev',
  'Ishaan',
  'Kabir',
  'Nikhil',
  'Sanjay',
  'Pranav',
  'Chen',
  'Hao',
  'Feng',
  'Bo',
  'Tao',
  'Kenji',
  'Ren',
  'Haruki',
  'Daichi',
  'Minho',
  'Chibuzo',
  'Emeka',
  'Obinna',
  'Kwame',
  'Sékou',
  'Jabari',
  'Amari',
  'Dontae',
  'Terrell',
  'Xavier',
  'Lars',
  'Anders',
  'Bjorn',
  'Mikael',
  'Stefan',
  'Janusz',
  'Dragan',
  'Niko',
  'Cillian',
  'Declan',
  'Vincent',
  'Patrick',
  'George',
  'Edward',
  'Albert',
  'Harold',
  'Eugene',
  'Leonard',
  'Vernon',
  'Roman',
];
export const LAST_NAMES = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Martinez',
  'Rodriguez',
  'Lopez',
  'Gonzalez',
  'Hernandez',
  'Nguyen',
  'Tran',
  'Pham',
  'Chen',
  'Wang',
  'Liu',
  'Kim',
  'Park',
  'Patel',
  'Singh',
  'Khan',
  'Ali',
  'Haddad',
  'Okafor',
  'Adeyemi',
  'Mensah',
  'Robinson',
  'Jackson',
  'Washington',
  'Brooks',
  'Foster',
  'Goldstein',
  'Cohen',
  'Romano',
  'Petrova',
  'Kowalski',
  'Andersson',
  'Rivera',
  'Mendez',
  'Ramirez',
  'Alvarez',
  'Castillo',
  'Reyes',
  'Webb',
  'Bennett',
  'Mitchell',
  'Carter',
  'Thompson',
  'Hayes',
  'Miller',
  'Davis',
  'Wilson',
  'Moore',
  'Taylor',
  'Anderson',
  'Thomas',
  'Harris',
  'Martin',
  'Clark',
  'Lewis',
  'Walker',
  'Hall',
  'Allen',
  'Young',
  'King',
  'Wright',
  'Scott',
  'Green',
  'Baker',
  'Adams',
  'Nelson',
  'Hill',
  'Campbell',
  'Roberts',
  'Phillips',
  'Evans',
  'Turner',
  'Parker',
  'Collins',
  'Edwards',
  'Stewart',
  'Morris',
  'Murphy',
  'Cook',
  'Rogers',
  'Morgan',
  'Cooper',
  'Reed',
  'Bailey',
  'Bell',
  'Gomez',
  'Kelly',
  'Howard',
  'Cruz',
  'Diaz',
  'Torres',
  'Flores',
  'Gutierrez',
  'Ortiz',
  'Morales',
  'Ramos',
  'Vargas',
  'Castro',
  'Jimenez',
  'Moreno',
  'Herrera',
  'Medina',
  'Aguilar',
  'Vega',
  'Delgado',
  'Guerrero',
  'Rojas',
  'Fuentes',
  'Cabrera',
  'Cardenas',
  'Salazar',
  'Mejia',
  'Pena',
  'Navarro',
  'Li',
  'Zhang',
  'Yang',
  'Huang',
  'Wu',
  'Zhou',
  'Xu',
  'Sun',
  'Ma',
  'Zhao',
  'Lee',
  'Choi',
  'Jung',
  'Kang',
  'Yoon',
  'Lim',
  'Sato',
  'Suzuki',
  'Takahashi',
  'Tanaka',
  'Watanabe',
  'Ito',
  'Yamamoto',
  'Nakamura',
  'Kobayashi',
  'Sharma',
  'Kumar',
  'Gupta',
  'Reddy',
  'Nair',
  'Iyer',
  'Mehta',
  'Joshi',
  'Desai',
  'Rao',
  'Malhotra',
  'Chowdhury',
  'Banerjee',
  'Das',
  'Bose',
  'Hassan',
  'Ahmed',
  'Mahmoud',
  'Saleh',
  'Nasser',
  'Aziz',
  'Rahman',
  'Farouk',
  'Mansour',
  'Karim',
  'Okonkwo',
  'Eze',
  'Abebe',
  'Diallo',
  'Traore',
  'Mwangi',
  'Osei',
  'Bello',
  'Achebe',
  'Nkemelu',
  'Williamson',
  'Fitzgerald',
  "O'Brien",
  'Murphy',
  'Kennedy',
  'Walsh',
  'Novak',
  'Horvath',
  'Schneider',
  'Weber',
  'Fischer',
  'Meyer',
  'Wagner',
  'Becker',
  'Hoffmann',
  'Schulz',
  'Richter',
  'Klein',
  'Wolf',
  'Schroeder',
  'Ivanov',
  'Sokolov',
  'Volkov',
  'Popov',
  'Kuznetsov',
  'Nowak',
  'Wójcik',
  'Kaminski',
  'Lewandowski',
  'Zielinski',
  'Russo',
  'Ferrari',
  'Esposito',
  'Bianchi',
  'Conti',
  'Greco',
  'Ricci',
  'Marino',
  'Costa',
  'Bruno',
  'Silva',
  'Santos',
  'Oliveira',
  'Souza',
  'Pereira',
  'Lima',
  'Carvalho',
  'Ribeiro',
  'Almeida',
  'Barbosa',
  // ── expanded pool (target ~650 distinct surnames; code dedups) ──
  'Cox',
  'Ward',
  'Richardson',
  'Watson',
  'Wood',
  'Gray',
  'Hughes',
  'Price',
  'Myers',
  'Long',
  'Ross',
  'Sanders',
  'Russell',
  'Griffin',
  'Powell',
  'Patterson',
  'Bryant',
  'Alexander',
  'Butler',
  'Barnes',
  'Fisher',
  'Henderson',
  'Coleman',
  'Simmons',
  'Jenkins',
  'Perry',
  'Gardner',
  'Stephens',
  'Payne',
  'Pierce',
  'Berry',
  'Matthews',
  'Arnold',
  'Willis',
  'Watkins',
  'Olson',
  'Carroll',
  'Duncan',
  'Snyder',
  'Hart',
  'Cunningham',
  'Bradley',
  'Lane',
  'Andrews',
  'Ruiz',
  'Harper',
  'Fox',
  'Riley',
  'Armstrong',
  'Carpenter',
  'Weaver',
  'Greene',
  'Lawrence',
  'Elliott',
  'Chavez',
  'Sims',
  'Austin',
  'Peters',
  'Kelley',
  'Franklin',
  'Lawson',
  'Fields',
  'Holmes',
  'Rose',
  'Stone',
  'Hawkins',
  'Dunn',
  'Perkins',
  'Hudson',
  'Spencer',
  'Gardner',
  'Wells',
  'Webster',
  'Holland',
  'Newman',
  'Pearson',
  'Curtis',
  'Freeman',
  'Burns',
  'Wallace',
  'Mason',
  'Knight',
  'Hamilton',
  'Graham',
  'Sullivan',
  'Wells',
  'Chapman',
  'Oliver',
  'Marshall',
  'Gibson',
  'Ellis',
  'Crawford',
  'Henderson',
  'Black',
  'Tucker',
  'Boyd',
  'Burton',
  'Fuller',
  'Banks',
  'Daniels',
  // Hispanic / Latino
  'Acosta',
  'Aguirre',
  'Benitez',
  'Cordova',
  'Dominguez',
  'Escobar',
  'Espinoza',
  'Galvan',
  'Gallardo',
  'Ibarra',
  'Juarez',
  'Lara',
  'Maldonado',
  'Marquez',
  'Montoya',
  'Nunez',
  'Ochoa',
  'Padilla',
  'Quintero',
  'Rios',
  'Sandoval',
  'Serrano',
  'Solis',
  'Soto',
  'Trujillo',
  'Valdez',
  'Velasquez',
  'Villanueva',
  'Zamora',
  'Zuniga',
  'Bautista',
  'Carrillo',
  'Cervantes',
  'Duran',
  'Estrada',
  'Figueroa',
  'Gallegos',
  'Guzman',
  'Leon',
  'Mata',
  'Molina',
  'Orozco',
  'Pacheco',
  'Pineda',
  'Rivas',
  'Rosales',
  'Salinas',
  'Tapia',
  'Vasquez',
  'Velez',
  // East Asian (Chinese / Korean / Japanese / Vietnamese)
  'Lin',
  'Zheng',
  'Guo',
  'He',
  'Gao',
  'Luo',
  'Song',
  'Tang',
  'Deng',
  'Han',
  'Feng',
  'Cao',
  'Peng',
  'Cheng',
  'Cai',
  'Yu',
  'Dong',
  'Xie',
  'Yuan',
  'Pan',
  'Jeong',
  'Cho',
  'Yoo',
  'Han',
  'Shin',
  'Oh',
  'Seo',
  'Kwon',
  'Hwang',
  'Ahn',
  'Yamada',
  'Sasaki',
  'Yamaguchi',
  'Matsumoto',
  'Inoue',
  'Kimura',
  'Hayashi',
  'Shimizu',
  'Mori',
  'Abe',
  'Le',
  'Vo',
  'Hoang',
  'Phan',
  'Vu',
  'Dang',
  'Bui',
  'Do',
  'Ho',
  'Ngo',
  // South Asian
  'Agarwal',
  'Bhatt',
  'Chauhan',
  'Chopra',
  'Deshpande',
  'Dixit',
  'Ganesan',
  'Ghosh',
  'Kapoor',
  'Khanna',
  'Krishnan',
  'Menon',
  'Mukherjee',
  'Pillai',
  'Prasad',
  'Raman',
  'Saxena',
  'Sengupta',
  'Shah',
  'Subramanian',
  'Trivedi',
  'Varma',
  'Verma',
  'Yadav',
  'Bhatia',
  'Chandra',
  'Dutta',
  'Kaur',
  'Naidu',
  'Sinha',
  // Middle Eastern / Arabic / Persian
  'Abadi',
  'Amini',
  'Bakir',
  'Darwish',
  'Fakhoury',
  'Ghanem',
  'Habib',
  'Ismail',
  'Jaber',
  'Kassab',
  'Khalil',
  'Maalouf',
  'Najjar',
  'Othman',
  'Qureshi',
  'Rahimi',
  'Sabbagh',
  'Shadid',
  'Tahan',
  'Yousef',
  'Ansari',
  'Bashir',
  'Daoud',
  'Hamdan',
  'Kazemi',
  'Mousavi',
  'Nazari',
  'Rashidi',
  'Sadeghi',
  'Zahed',
  // African (West / East / Southern)
  'Adebayo',
  'Afolabi',
  'Balogun',
  'Chukwu',
  'Danjuma',
  'Eze',
  'Ibrahim',
  'Kamara',
  'Lawal',
  'Mbeki',
  'Ndiaye',
  'Nwosu',
  'Obi',
  'Olawale',
  'Owusu',
  'Sankara',
  'Sesay',
  'Tetteh',
  'Uche',
  'Zewde',
  'Asante',
  'Banda',
  'Dube',
  'Khumalo',
  'Mabaso',
  'Mensa',
  'Moyo',
  'Ndlovu',
  'Okeke',
  'Sibanda',
  // European (German / Italian / Polish / Russian / Greek / French / Scandinavian / Irish)
  'Bauer',
  'Braun',
  'Hartmann',
  'Keller',
  'Koch',
  'Lang',
  'Neumann',
  'Schmitt',
  'Vogel',
  'Zimmermann',
  'Colombo',
  'Ferri',
  'Gallo',
  'Lombardi',
  'Mancini',
  'Moretti',
  'Rizzo',
  'Romano',
  'Serra',
  'Villa',
  'Dabrowski',
  'Jankowski',
  'Mazur',
  'Pawlak',
  'Sikora',
  'Szymanski',
  'Wozniak',
  'Zajac',
  'Krawczyk',
  'Wieczorek',
  'Fedorov',
  'Morozov',
  'Pavlov',
  'Romanov',
  'Smirnov',
  'Vasiliev',
  'Zaytsev',
  'Egorov',
  'Orlov',
  'Komarov',
  'Pappas',
  'Nikolaou',
  'Georgiou',
  'Vasilakis',
  'Dimitriou',
  'Antoniou',
  'Christou',
  'Petrou',
  'Stavros',
  'Manos',
  'Dubois',
  'Laurent',
  'Lefebvre',
  'Moreau',
  'Girard',
  'Bonnet',
  'Rousseau',
  'Mercier',
  'Blanc',
  'Henry',
  'Larsen',
  'Hansen',
  'Pedersen',
  'Nilsson',
  'Eriksson',
  'Lindholm',
  'Bergstrom',
  'Dahl',
  'Holm',
  'Sandberg',
  'Doyle',
  'Gallagher',
  'Lynch',
  'Brennan',
  'Byrne',
  'Connolly',
  'Donovan',
  'Flanagan',
  'Quinn',
  'Sheridan',
  // ── final fill to ~650 distinct ──
  'Pratt',
  'Schwartz',
  'Mccarthy',
  'Vaughn',
  'Norris',
  'Briggs',
  'Mullins',
  'Hester',
  'Frost',
  'Pope',
  'Yates',
  'Conway',
  'Floyd',
  'Barron',
  'Cherry',
  'Bridges',
  'Hopkins',
  'Mack',
  'Compton',
  'Sutton',
  'Maxwell',
  'Vance',
  'Roach',
  'Calderon',
  'Bravo',
  'Ferreira',
  'Aquino',
  'Cordero',
  'Espinosa',
  'Galindo',
  'Mahmood',
  'Siddiqui',
  'Farooqi',
  'Chaudhry',
  'Baig',
  'Iqbal',
  'Rizvi',
  'Zaidi',
  'Hashmi',
  'Sheikh',
  'Tariq',
  'Haidar',
  'Khoury',
  'Saliba',
  'Aoun',
  'Gerges',
  'Bishara',
  'Mikhail',
  'Sayegh',
  'Touma',
  'Adeyemo',
  'Olaniyan',
  'Ogunyemi',
  'Adesanya',
  'Babatunde',
  'Falade',
  'Ojo',
  'Salami',
  'Akinyele',
  'Bamidele',
  'Ostrowski',
  'Witkowski',
  'Baranski',
  'Sobczak',
  'Michalski',
  'Adamczyk',
  'Dudek',
  'Wroblewski',
  'Kozlowski',
  'Jasinski',
];

// Staff rosters by location — must match the names created by
// link-synth-staff-users.ts (see SYNTH-STAFF.md). Providers are passed via
// --practitioner (attending); MAs via --intake.
export const PROVIDERS_BY_LOCATION: Record<string, string[]> = {
  'Los Angeles': ['Maria Alvarez', 'James Okafor', 'Priya Nair', 'Daniel Cohen', 'Sofia Ramirez', 'Wei Chen'],
  'New York': ['Aisha Patel', "Liam O'Brien", 'Grace Kim', 'Marcus Webb', 'Elena Petrova', 'Samuel Adeyemi'],
};
export const MAS_BY_LOCATION: Record<string, string[]> = {
  'Los Angeles': ['Jasmine Lee', 'Carlos Mendez', 'Tanya Robinson'],
  'New York': ['Destiny Brooks', 'Omar Haddad', 'Lucia Romano'],
};
export const IN_PERSON_LOCATIONS = ['Los Angeles', 'New York'];
