import Oystehr from '@oystehr/sdk';
import { randomUUID } from 'crypto';
import { DocumentReference, List } from 'fhir/r4b';
import { DateTime } from 'luxon';
import {
  BUCKET_NAMES,
  FAX_DOCUMENT_ORDER,
  FAX_PACKET_MAX_BYTES,
  FAX_PACKET_MAX_PAGES,
  FaxDocumentKind,
  FaxRecipient,
  Secrets,
} from 'utils';
import { createFaxCoverSheetPdfBytes } from '../pdf/fax-cover-sheet-pdf';
import { makeFaxPacketDocumentReference } from '../pdf/make-fax-packet-document-reference';
import { downloadPdfBytes, mergePdfDocuments } from '../pdf/merge-pdfs';
import { PdfInfo } from '../pdf/pdf-utils';
import { FaxCoverSheetData } from '../pdf/types';
import { FullAppointmentResourcePackage } from '../pdf/visit-details-pdf/types';
import { makeZ3Url } from '../presigned-file-urls';
import { createPresignedUrl, uploadObjectToZ3 } from '../z3Utils';
import { collectFaxParts, FaxPacketPart } from './collect-visit-documents';

/**
 * The selected visit documents merged into one PDF, without a cover sheet.
 *
 * For now the body is identical for every recipient (only the cover sheet differs), so it is built once per
 * request and reused. If recipients later get per-recipient options that affect the body, this will need to
 * be rebuilt per recipient.
 */
export interface FaxPacketBody {
  bytes: Uint8Array;
  pageCount: number;
  parts: FaxPacketPart[];
}

const MAX_BYTES_MB = (FAX_PACKET_MAX_BYTES / (1024 * 1024)).toFixed(0);

export async function buildFaxPacketBody(args: {
  oystehr: Oystehr;
  token: string;
  secrets: Secrets | null;
  kinds?: FaxDocumentKind[];
  visitResources: FullAppointmentResourcePackage;
}): Promise<FaxPacketBody> {
  const { oystehr, token, secrets, visitResources } = args;
  const kinds = args.kinds ?? FAX_DOCUMENT_ORDER;

  const parts = await collectFaxParts({ oystehr, token, secrets, kinds, visitResources });
  if (parts.length === 0) {
    throw new Error('No documents could be collected for the fax packet. Nothing was sent.');
  }

  const partBytes = await Promise.all(
    parts.map(async (part) => {
      if (part.bytes) return part.bytes;
      if (!part.z3Url) throw new Error(`Fax packet part "${part.title}" has neither generated bytes nor a stored file`);
      return downloadPdfBytes(part.z3Url, token);
    })
  );

  const { bytes, pageCount } = await mergePdfDocuments(partBytes);
  console.log(`Built fax packet body: ${parts.length} document(s), ${pageCount} page(s)`);
  return { bytes, pageCount, parts };
}

/**
 * Renders the recipient's cover sheet, merges it in front of the already-built body, enforces the
 * transmission limits and uploads the result, then records it as a DocumentReference.
 *
 * Never re-collects or re-merges the body: `body` is passed in precisely so that a multi-recipient
 * send does that work once.
 */
export async function buildAndUploadPacketForRecipient(args: {
  oystehr: Oystehr;
  token: string;
  secrets: Secrets | null;
  body: FaxPacketBody;
  recipient: FaxRecipient;
  /** Subject + sender are supplied by the caller; recipient and totalPages are filled in here. */
  coverSheet: Omit<FaxCoverSheetData, 'totalPages' | 'recipient'>;
  patientId: string;
  appointmentId: string;
  encounterId: string;
  listResources: List[];
}): Promise<{ pdfInfo: PdfInfo; documentReference: DocumentReference; pageCount: number }> {
  const { oystehr, token, secrets, body, recipient, coverSheet, patientId, appointmentId, encounterId, listResources } =
    args;

  const coverData: Omit<FaxCoverSheetData, 'totalPages'> = {
    ...coverSheet,
    recipient: {
      name: recipient.name,
      organization: recipient.organization,
      faxNumber: recipient.faxNumber,
      phoneNumber: recipient.phoneNumber,
    },
  };

  // The cover sheet prints the packet's total page count, which depends on how long the cover sheet
  // itself is. One correction pass is enough: the count only ever grows the footer text.
  let coverBytes = await createFaxCoverSheetPdfBytes({ ...coverData, totalPages: 1 + body.pageCount });
  let merged = await mergePdfDocuments([coverBytes, body.bytes]);
  const coverPages = merged.pageCount - body.pageCount;

  if (coverPages !== 1) {
    coverBytes = await createFaxCoverSheetPdfBytes({ ...coverData, totalPages: coverPages + body.pageCount });
    merged = await mergePdfDocuments([coverBytes, body.bytes]);
  }

  // Enforced before the upload so an oversized packet leaves nothing behind in storage.
  if (merged.pageCount > FAX_PACKET_MAX_PAGES) {
    throw new Error(
      `Fax packet is ${merged.pageCount} pages, which exceeds the ${FAX_PACKET_MAX_PAGES} page limit. ` +
        'Select fewer documents and try again.'
    );
  }
  if (merged.bytes.length > FAX_PACKET_MAX_BYTES) {
    throw new Error(
      `Fax packet is ${(merged.bytes.length / (1024 * 1024)).toFixed(1)} MB, which exceeds the ${MAX_BYTES_MB} MB ` +
        'limit. Select fewer documents and try again.'
    );
  }

  // A retry must re-send the original bytes, so every packet is its own immutable file: the unique
  // filename doubles as the DocumentReference title, which is what keeps earlier packets from being
  // superseded (see makeFaxPacketDocumentReference).
  const fileName = `FaxPacket-${DateTime.now().toUTC().toFormat('yyyy-MM-dd-HHmmss')}-${randomUUID()}.pdf`;

  const uploadURL = makeZ3Url({
    secrets,
    bucketName: BUCKET_NAMES.FAXES,
    patientID: patientId,
    fileName,
  });

  const presignedUploadUrl = await createPresignedUrl(token, uploadURL, 'upload');

  await uploadObjectToZ3(merged.bytes, presignedUploadUrl);

  const pdfInfo: PdfInfo = { title: fileName, uploadURL };

  const documentReference = await makeFaxPacketDocumentReference({
    oystehr,
    pdfInfo,
    patientId,
    appointmentId,
    encounterId,
    listResources,
  });

  return { pdfInfo, documentReference, pageCount: merged.pageCount };
}
