import { ExamCardsNames, ExamFieldsNames, ExamObservationDTO } from 'ehr-utils';
import { ExamTabProviderCardNames, ExamObservationFieldItem } from '../../types/types';

export const ExamObservationCardsDetails: {
  [field in ExamCardsNames]: {
    field: ExamCardsNames;
    defaultValue: string;
    card: ExamTabProviderCardNames;
  };
} = {
  'general-comment': { field: 'general-comment', defaultValue: '', card: 'general' },
  'head-comment': { field: 'head-comment', defaultValue: '', card: 'head' },
  'eyes-comment': { field: 'eyes-comment', defaultValue: '', card: 'eyes' },
  'nose-comment': { field: 'nose-comment', defaultValue: '', card: 'nose' },
  'ears-comment': { field: 'ears-comment', defaultValue: '', card: 'ears' },
  'mouth-comment': { field: 'mouth-comment', defaultValue: '', card: 'mouth' },
  'neck-comment': { field: 'neck-comment', defaultValue: '', card: 'neck' },
  'chest-comment': { field: 'chest-comment', defaultValue: '', card: 'chest' },
  'abdomen-comment': { field: 'abdomen-comment', defaultValue: '', card: 'abdomen' },
  'back-comment': { field: 'back-comment', defaultValue: '', card: 'back' },
  'skin-comment': { field: 'skin-comment', defaultValue: '', card: 'skin' },
  'extremities-musculoskeletal-comment': {
    field: 'extremities-musculoskeletal-comment',
    defaultValue: '',
    card: 'musculoskeletal',
  },
  'neurological-comment': { field: 'neurological-comment', defaultValue: '', card: 'neurological' },
  'psych-comment': { field: 'psych-comment', defaultValue: '', card: 'psych' },
};

export const ExamObservationFieldsDetails: {
  [field in ExamFieldsNames]: ExamObservationFieldItem;
} = {
  // >>> CARD = general
  // >> GROUP = normal
  alert: { field: 'alert', defaultValue: true, abnormal: false, group: 'normal', card: 'general', label: 'Alert' },
  awake: { field: 'awake', defaultValue: true, abnormal: false, group: 'normal', card: 'general', label: 'Awake' },
  calm: { field: 'calm', defaultValue: true, abnormal: false, group: 'normal', card: 'general', label: 'Calm' },
  'well-hydrated': {
    field: 'well-hydrated',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'general',
    label: 'Well hydrated',
  },
  'moist-mucous-membrane': {
    field: 'moist-mucous-membrane',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'general',
    label: 'MMM (Moist Mucous Membrane)',
  },
  'distress-none': {
    field: 'distress-none',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'general',
    label: 'No distress',
  },
  'playful-and-active': {
    field: 'playful-and-active',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'general',
    label: 'Playful and active',
  },
  // >> GROUP = abnormal
  'tired-appearing': {
    field: 'tired-appearing',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'general',
    label: 'Tired-appearing',
  },
  'ill-appearing': {
    field: 'ill-appearing',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'general',
    label: 'Ill-appearing',
  },
  fussy: { field: 'fussy', defaultValue: false, abnormal: true, group: 'abnormal', card: 'general', label: 'Fussy' },
  'dry-mucous-membranes': {
    field: 'dry-mucous-membranes',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'general',
    label: 'Dry mucous membranes',
  },
  'sunken-eye': {
    field: 'sunken-eye',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'general',
    label: 'Sunken eyes',
  },
  'mild-distress': {
    field: 'mild-distress',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'general',
    label: 'Mild',
  },
  'moderate-distress': {
    field: 'moderate-distress',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'general',
    label: 'Moderate',
  },
  'severe-distress': {
    field: 'severe-distress',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'general',
    label: 'Severe',
  },
  // >>> CARD = head
  // >> GROUP = normal
  normocephaly: {
    field: 'normocephaly',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'head',
    label: 'Normocephaly',
  },
  atraumatic: {
    field: 'atraumatic',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'head',
    label: 'Atraumatic',
  },
  // >>> CARD = eyes
  // >> GROUP = normal
  'pupils-symmetric': {
    field: 'pupils-symmetric',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'eyes',
    label: 'Pupils symmetric',
  },
  eomi: {
    field: 'eomi',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'eyes',
    label: 'EOMI (Extra Ocular Movements Intact)',
  },
  // >> GROUP = abnormal
  'pupils-asymmetric': {
    field: 'pupils-asymmetric',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'eyes',
    label: 'Pupils asymmetric',
  },
  // >> GROUP = rightEye
  'right-eye-normal': {
    field: 'right-eye-normal',
    defaultValue: true,
    abnormal: false,
    group: 'rightEye',
    card: 'eyes',
    label: 'Normal',
  },
  'right-eye-injected': {
    field: 'right-eye-injected',
    defaultValue: false,
    abnormal: true,
    group: 'rightEye',
    card: 'eyes',
    label: 'Injected',
  },
  'right-eye-discharge': {
    field: 'right-eye-discharge',
    defaultValue: false,
    abnormal: true,
    group: 'rightEye',
    card: 'eyes',
    label: 'Discharge',
  },
  'right-eye-watering': {
    field: 'right-eye-watering',
    defaultValue: false,
    abnormal: true,
    group: 'rightEye',
    card: 'eyes',
    label: 'Watering',
  },
  'right-eye-puffy-eyelids': {
    field: 'right-eye-puffy-eyelids',
    defaultValue: false,
    abnormal: true,
    group: 'rightEye',
    card: 'eyes',
    label: 'Puffy eyelids',
  },
  'right-eye-small-round-mass-in-eyelid': {
    field: 'right-eye-small-round-mass-in-eyelid',
    defaultValue: false,
    abnormal: true,
    group: 'rightEye',
    card: 'eyes',
    label: 'Small round mass in eyelid',
  },
  // >> GROUP = leftEye
  'left-eye-normal': {
    field: 'left-eye-normal',
    defaultValue: true,
    abnormal: false,
    group: 'leftEye',
    card: 'eyes',
    label: 'Normal',
  },
  'left-eye-injected': {
    field: 'left-eye-injected',
    defaultValue: false,
    abnormal: true,
    group: 'leftEye',
    card: 'eyes',
    label: 'Injected',
  },
  'left-eye-discharge': {
    field: 'left-eye-discharge',
    defaultValue: false,
    abnormal: true,
    group: 'leftEye',
    card: 'eyes',
    label: 'Discharge',
  },
  'left-eye-watering': {
    field: 'left-eye-watering',
    defaultValue: false,
    abnormal: true,
    group: 'leftEye',
    card: 'eyes',
    label: 'Watering',
  },
  'left-eye-puffy-eyelids': {
    field: 'left-eye-puffy-eyelids',
    defaultValue: false,
    abnormal: true,
    group: 'leftEye',
    card: 'eyes',
    label: 'Puffy eyelids',
  },
  'left-eye-small-round-mass-in-eyelid': {
    field: 'left-eye-small-round-mass-in-eyelid',
    defaultValue: false,
    abnormal: true,
    group: 'leftEye',
    card: 'eyes',
    label: 'Small round mass in eyelid',
  },
  // >>> CARD = nose
  // >> GROUP = normal
  'no-drainage': {
    field: 'no-drainage',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'nose',
    label: 'No drainage',
  },
  // >> GROUP = abnormal
  'clear-rhinorrhea': {
    field: 'clear-rhinorrhea',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'nose',
    label: 'Clear rhinorrhea',
  },
  'purulent-discharge': {
    field: 'purulent-discharge',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'nose',
    label: 'Purulent discharge',
  },
  // >>> CARD = ears
  // >> GROUP = rightEar
  'normal-ear-right': {
    field: 'normal-ear-right',
    defaultValue: true,
    abnormal: false,
    group: 'rightEar',
    card: 'ears',
    label: 'Normal',
  },
  'erythema-ear-right': {
    field: 'erythema-ear-right',
    defaultValue: false,
    abnormal: true,
    group: 'rightEar',
    card: 'ears',
    label: 'Erythema',
  },
  'swelling-ear-right': {
    field: 'swelling-ear-right',
    defaultValue: false,
    abnormal: true,
    group: 'rightEar',
    card: 'ears',
    label: 'Swelling',
  },
  'pain-with-movement-of-pinna-ear-right': {
    field: 'pain-with-movement-of-pinna-ear-right',
    defaultValue: false,
    abnormal: true,
    group: 'rightEar',
    card: 'ears',
    label: 'Pain with movement of pinna',
  },
  'drainage-from-ear-canal-right': {
    field: 'drainage-from-ear-canal-right',
    defaultValue: false,
    abnormal: true,
    group: 'rightEar',
    card: 'ears',
    label: 'Drainage from ear canal',
  },
  'clear-discharge-ear-right': {
    field: 'clear-discharge-ear-right',
    defaultValue: false,
    abnormal: true,
    group: 'rightEar',
    card: 'ears',
    label: 'Clear discharge',
  },
  // >> GROUP = leftEar
  'normal-ear-left': {
    field: 'normal-ear-left',
    defaultValue: true,
    abnormal: false,
    group: 'leftEar',
    card: 'ears',
    label: 'Normal',
  },
  'erythema-ear-left': {
    field: 'erythema-ear-left',
    defaultValue: false,
    abnormal: true,
    group: 'leftEar',
    card: 'ears',
    label: 'Erythema',
  },
  'swelling-ear-left': {
    field: 'swelling-ear-left',
    defaultValue: false,
    abnormal: true,
    group: 'leftEar',
    card: 'ears',
    label: 'Swelling',
  },
  'pain-with-movement-of-pinna-ear-left': {
    field: 'pain-with-movement-of-pinna-ear-left',
    defaultValue: false,
    abnormal: true,
    group: 'leftEar',
    card: 'ears',
    label: 'Pain with movement of pinna',
  },
  'drainage-from-ear-canal-left': {
    field: 'drainage-from-ear-canal-left',
    defaultValue: false,
    abnormal: true,
    group: 'leftEar',
    card: 'ears',
    label: 'Drainage from ear canal',
  },
  'clear-discharge-ear-left': {
    field: 'clear-discharge-ear-left',
    defaultValue: false,
    abnormal: true,
    group: 'leftEar',
    card: 'ears',
    label: 'Clear discharge',
  },
  // >>> CARD = mouth
  // >> GROUP = normal
  'mouth-normal': {
    field: 'mouth-normal',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'mouth',
    label: 'Normal',
  },
  'mouth-moist-mucous-membrane': {
    field: 'mouth-moist-mucous-membrane',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'mouth',
    label: 'MMM (Moist Mucous Membrane)',
  },
  'normal-tongue': {
    field: 'normal-tongue',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'mouth',
    label: 'Normal tongue',
  },
  'uvula-midline': {
    field: 'uvula-midline',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'mouth',
    label: 'Uvula midline',
  },
  'tonsils-symmetric-and-not-enlarged': {
    field: 'tonsils-symmetric-and-not-enlarged',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'mouth',
    label: 'Tonsils symmetric and not enlarged',
  },
  'normal-voice': {
    field: 'normal-voice',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'mouth',
    label: 'Normal voice',
  },
  // >> GROUP = abnormal
  'mouth-dry-mucous-membranes': {
    field: 'mouth-dry-mucous-membranes',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Dry mucous membranes',
  },
  'erythema-of-pharynx': {
    field: 'erythema-of-pharynx',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Erythema of pharynx',
  },
  'white-patches-on-tongue-andor-buccal-mucosa-that-do-not-wipe-off': {
    field: 'white-patches-on-tongue-andor-buccal-mucosa-that-do-not-wipe-off',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'White patches on tongue and/or buccal mucosa that do not wipe off',
  },
  'strawberry-tongue': {
    field: 'strawberry-tongue',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Strawberry tongue',
  },
  'uvula-deviated': {
    field: 'uvula-deviated',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Uvula deviated',
  },
  'tonsils-erythematous': {
    field: 'tonsils-erythematous',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Tonsils erythematous',
  },
  'exudate-on-tonsils': {
    field: 'exudate-on-tonsils',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Exudate on tonsils',
  },
  'hoarse-voice': {
    field: 'hoarse-voice',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Hoarse voice',
  },
  'hot-potato-voice': {
    field: 'hot-potato-voice',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'mouth',
    label: 'Hot potato voice',
  },
  // >>> CARD = neck
  // >> GROUP = normal
  'supple-neck': {
    field: 'supple-neck',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'neck',
    label: 'Supple',
  },
  'moves-in-all-directions': {
    field: 'moves-in-all-directions',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'neck',
    label: 'Moves in all directions',
  },
  // >>> CARD = chest
  // >> GROUP = normal
  'normal-respiratory-effort': {
    field: 'normal-respiratory-effort',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'chest',
    label: 'Normal respiratory effort',
  },
  'no-tachypnea': {
    field: 'no-tachypnea',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'chest',
    label: 'No tachypnea',
  },
  'no-retractions': {
    field: 'no-retractions',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'chest',
    label: 'No retractions',
  },
  'no-conversational-dyspnea': {
    field: 'no-conversational-dyspnea',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'chest',
    label: 'No conversational dyspnea',
  },
  // >> GROUP = abnormal
  tachypnea: {
    field: 'tachypnea',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Tachypnea',
  },
  'suprasternal-retractions': {
    field: 'suprasternal-retractions',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Suprasternal retractions',
  },
  'intercostal-retractions': {
    field: 'intercostal-retractions',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Intercostal retractions',
  },
  'subcostal-retractions': {
    field: 'subcostal-retractions',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Subcostal retractions',
  },
  'abdominal-breathing': {
    field: 'abdominal-breathing',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Abdominal breathing',
  },
  grunting: {
    field: 'grunting',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Grunting',
  },
  'nasal-flaring': {
    field: 'nasal-flaring',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Nasal flaring',
  },
  wheeze: {
    field: 'wheeze',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Audible wheeze',
  },
  'barky-cough': {
    field: 'barky-cough',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Barky cough',
  },
  'stridor-with-each-breath': {
    field: 'stridor-with-each-breath',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'chest',
    label: 'Stridor with each breath',
  },
  // >>> CARD = back
  // >> GROUP = normal
  'back-normal': {
    field: 'back-normal',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'back',
    label: 'Normal',
  },
  'able-to-flex-and-extend-back-and-move-side-to-side': {
    field: 'able-to-flex-and-extend-back-and-move-side-to-side',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'back',
    label: 'Able to flex and extend back and twist side to side',
  },
  // >> GROUP = abnormal
  'cva-tenderness': {
    field: 'cva-tenderness',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'back',
    label: 'CVA tenderness',
  },
  // >>> CARD = skin
  // >> GROUP = normal
  'no-rashes': {
    field: 'no-rashes',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'skin',
    label: 'No rashes',
  },
  // >> GROUP = form
  'consistent-with-viral-exam': {
    field: 'consistent-with-viral-exam',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with viral exam',
  },
  'consistent-with-insect-bites': {
    field: 'consistent-with-insect-bites',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with insect bites',
  },
  'consistent-with-urticaria': {
    field: 'consistent-with-urticaria',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with urticaria',
  },
  'consistent-with-coxsackievirus': {
    field: 'consistent-with-coxsackievirus',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with Coxsackievirus',
  },
  'consistent-with-irritant-diaper-rash': {
    field: 'consistent-with-irritant-diaper-rash',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with irritant diaper rash',
  },
  'consistent-with-ringworm': {
    field: 'consistent-with-ringworm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with ringworm',
  },
  'consistent-with-impetigo': {
    field: 'consistent-with-impetigo',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with impetigo',
  },
  'consistent-with-fifths-disease': {
    field: 'consistent-with-fifths-disease',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: "consistent with Fifth's disease",
  },
  'consistent-with-atopic-dermatitis': {
    field: 'consistent-with-atopic-dermatitis',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with atopic dermatitis',
  },
  'consistent-with-paronychia': {
    field: 'consistent-with-paronychia',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with paronychia',
  },
  'consistent-with-poison-ivy-contact-dermatitis': {
    field: 'consistent-with-poison-ivy-contact-dermatitis',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with poison ivy contact dermatitis',
  },
  'consistent-with-tinea-capitis': {
    field: 'consistent-with-tinea-capitis',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with tinea capitis',
  },
  'consistent-with-pityriasis-rosea': {
    field: 'consistent-with-pityriasis-rosea',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with pityriasis rosea',
  },
  'consistent-with-lyme-ecm': {
    field: 'consistent-with-lyme-ecm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'skin',
    label: 'consistent with Lyme ECM',
  },
  // >>> CARD = abdomen
  // >> GROUP = normal
  'normal-appearing-on-parental-exam': {
    field: 'normal-appearing-on-parental-exam',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'abdomen',
    label: 'Normal appearing on parental exam',
  },
  'non-tender-on-parental-exam': {
    field: 'non-tender-on-parental-exam',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'abdomen',
    label: 'Non-tender on parental exam',
  },
  'able-to-jump-up-down-without-abdominal-pain': {
    field: 'able-to-jump-up-down-without-abdominal-pain',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'abdomen',
    label: 'Able to jump up/down without abdominal pain',
  },
  // >> GROUP = abnormal
  'left-lower-quadrant-abdomen': {
    field: 'left-lower-quadrant-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Left Lower Quadrant - Abdomen',
  },
  'right-lower-quadrant-abdomen': {
    field: 'right-lower-quadrant-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Right Lower Quadrant - Abdomen',
  },
  'right-upper-quadrant-abdomen': {
    field: 'right-upper-quadrant-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Right Upper Quadrant - Abdomen',
  },
  'left-upper-quadrant-abdomen': {
    field: 'left-upper-quadrant-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Left Upper Quadrant - Abdomen',
  },
  'epigastric-region-abdomen': {
    field: 'epigastric-region-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Epigastric Region - Abdomen',
  },
  'left-abdominal-lumbar-region-abdomen': {
    field: 'left-abdominal-lumbar-region-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Left Abdominal Lumbar Region - Abdomen',
  },
  'right-abdominal-lumbar-region-abdomen': {
    field: 'right-abdominal-lumbar-region-abdomen',
    defaultValue: false,
    abnormal: true,
    group: 'dropdown',
    card: 'abdomen',
    label: 'Right Abdominal Lumbar Region - Abdomen',
  },
  'not-able-to-jump-up-down-due-to-abdominal-pain': {
    field: 'not-able-to-jump-up-down-due-to-abdominal-pain',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'abdomen',
    label: 'Not able to jump up/down due to abdominal pain',
  },
  // >>> CARD = musculoskeletal
  // >> GROUP = normal
  'moving-extemities-equally': {
    field: 'moving-extemities-equally',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'musculoskeletal',
    label: 'Moving extemities equally',
  },
  'normal-gait': {
    field: 'normal-gait',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'musculoskeletal',
    label: 'Normal gait',
  },
  'normal-rom': {
    field: 'normal-rom',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'musculoskeletal',
    label: 'Normal ROM',
  },
  'no-swelling': {
    field: 'no-swelling',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'musculoskeletal',
    label: 'No swelling',
  },
  'no-bruising': {
    field: 'no-bruising',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'musculoskeletal',
    label: 'No bruising',
  },
  'no-deformity': {
    field: 'no-deformity',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'musculoskeletal',
    label: 'No deformity',
  },
  // >> GROUP = form
  'swelling-left-finger-index': {
    field: 'swelling-left-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-finger-index': {
    field: 'swelling-right-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-finger-middle': {
    field: 'swelling-left-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-finger-middle': {
    field: 'swelling-right-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-finger-ring': {
    field: 'swelling-left-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-finger-ring': {
    field: 'swelling-right-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-finger-little': {
    field: 'swelling-left-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-finger-little': {
    field: 'swelling-right-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-finger-thumb': {
    field: 'swelling-left-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-finger-thumb': {
    field: 'swelling-right-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-hand': {
    field: 'swelling-left-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-hand': {
    field: 'swelling-right-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-foot': {
    field: 'swelling-left-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-foot': {
    field: 'swelling-right-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-toe-great': {
    field: 'swelling-left-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-toe-great': {
    field: 'swelling-right-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-toe-second': {
    field: 'swelling-left-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-toe-second': {
    field: 'swelling-right-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-toe-third': {
    field: 'swelling-left-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-toe-third': {
    field: 'swelling-right-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-toe-fourth': {
    field: 'swelling-left-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-toe-fourth': {
    field: 'swelling-right-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-toe-fifth': {
    field: 'swelling-left-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-toe-fifth': {
    field: 'swelling-right-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-wrist': {
    field: 'swelling-left-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-wrist': {
    field: 'swelling-right-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-forearm': {
    field: 'swelling-left-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-forearm': {
    field: 'swelling-right-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-elbow': {
    field: 'swelling-left-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-elbow': {
    field: 'swelling-right-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-upperarm': {
    field: 'swelling-left-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-upperarm': {
    field: 'swelling-right-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-shoulder': {
    field: 'swelling-left-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-shoulder': {
    field: 'swelling-right-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-knee': {
    field: 'swelling-left-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-knee': {
    field: 'swelling-right-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-lowerleg': {
    field: 'swelling-left-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-lowerleg': {
    field: 'swelling-right-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-left-ankle': {
    field: 'swelling-left-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'swelling-right-ankle': {
    field: 'swelling-right-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-finger-index': {
    field: 'deformity-left-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-finger-index': {
    field: 'deformity-right-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-finger-middle': {
    field: 'deformity-left-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-finger-middle': {
    field: 'deformity-right-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-finger-ring': {
    field: 'deformity-left-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-finger-ring': {
    field: 'deformity-right-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-finger-little': {
    field: 'deformity-left-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-finger-little': {
    field: 'deformity-right-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-finger-thumb': {
    field: 'deformity-left-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-finger-thumb': {
    field: 'deformity-right-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-hand': {
    field: 'deformity-left-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-hand': {
    field: 'deformity-right-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-foot': {
    field: 'deformity-left-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-foot': {
    field: 'deformity-right-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-toe-great': {
    field: 'deformity-left-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-toe-great': {
    field: 'deformity-right-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-toe-second': {
    field: 'deformity-left-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-toe-second': {
    field: 'deformity-right-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-toe-third': {
    field: 'deformity-left-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-toe-third': {
    field: 'deformity-right-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-toe-fourth': {
    field: 'deformity-left-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-toe-fourth': {
    field: 'deformity-right-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-toe-fifth': {
    field: 'deformity-left-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-toe-fifth': {
    field: 'deformity-right-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-wrist': {
    field: 'deformity-left-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-wrist': {
    field: 'deformity-right-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-forearm': {
    field: 'deformity-left-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-forearm': {
    field: 'deformity-right-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-elbow': {
    field: 'deformity-left-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-elbow': {
    field: 'deformity-right-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-upperarm': {
    field: 'deformity-left-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-upperarm': {
    field: 'deformity-right-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-shoulder': {
    field: 'deformity-left-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-shoulder': {
    field: 'deformity-right-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-knee': {
    field: 'deformity-left-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-knee': {
    field: 'deformity-right-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-lowerleg': {
    field: 'deformity-left-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-lowerleg': {
    field: 'deformity-right-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-left-ankle': {
    field: 'deformity-left-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'deformity-right-ankle': {
    field: 'deformity-right-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-finger-index': {
    field: 'bruising-left-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-finger-index': {
    field: 'bruising-right-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-finger-middle': {
    field: 'bruising-left-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-finger-middle': {
    field: 'bruising-right-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-finger-ring': {
    field: 'bruising-left-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-finger-ring': {
    field: 'bruising-right-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-finger-little': {
    field: 'bruising-left-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-finger-little': {
    field: 'bruising-right-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-finger-thumb': {
    field: 'bruising-left-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-finger-thumb': {
    field: 'bruising-right-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-hand': {
    field: 'bruising-left-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-hand': {
    field: 'bruising-right-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-foot': {
    field: 'bruising-left-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-foot': {
    field: 'bruising-right-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-toe-great': {
    field: 'bruising-left-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-toe-great': {
    field: 'bruising-right-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-toe-second': {
    field: 'bruising-left-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-toe-second': {
    field: 'bruising-right-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-toe-third': {
    field: 'bruising-left-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-toe-third': {
    field: 'bruising-right-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-toe-fourth': {
    field: 'bruising-left-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-toe-fourth': {
    field: 'bruising-right-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-toe-fifth': {
    field: 'bruising-left-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-toe-fifth': {
    field: 'bruising-right-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-wrist': {
    field: 'bruising-left-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-wrist': {
    field: 'bruising-right-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-forearm': {
    field: 'bruising-left-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-forearm': {
    field: 'bruising-right-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-elbow': {
    field: 'bruising-left-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-elbow': {
    field: 'bruising-right-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-upperarm': {
    field: 'bruising-left-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-upperarm': {
    field: 'bruising-right-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-shoulder': {
    field: 'bruising-left-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-shoulder': {
    field: 'bruising-right-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-knee': {
    field: 'bruising-left-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-knee': {
    field: 'bruising-right-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-lowerleg': {
    field: 'bruising-left-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-lowerleg': {
    field: 'bruising-right-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-left-ankle': {
    field: 'bruising-left-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'bruising-right-ankle': {
    field: 'bruising-right-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-finger-index': {
    field: 'abletobearweight-left-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-finger-index': {
    field: 'abletobearweight-right-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-finger-middle': {
    field: 'abletobearweight-left-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-finger-middle': {
    field: 'abletobearweight-right-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-finger-ring': {
    field: 'abletobearweight-left-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-finger-ring': {
    field: 'abletobearweight-right-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-finger-little': {
    field: 'abletobearweight-left-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-finger-little': {
    field: 'abletobearweight-right-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-finger-thumb': {
    field: 'abletobearweight-left-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-finger-thumb': {
    field: 'abletobearweight-right-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-hand': {
    field: 'abletobearweight-left-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-hand': {
    field: 'abletobearweight-right-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-foot': {
    field: 'abletobearweight-left-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-foot': {
    field: 'abletobearweight-right-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-toe-great': {
    field: 'abletobearweight-left-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-toe-great': {
    field: 'abletobearweight-right-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-toe-second': {
    field: 'abletobearweight-left-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-toe-second': {
    field: 'abletobearweight-right-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-toe-third': {
    field: 'abletobearweight-left-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-toe-third': {
    field: 'abletobearweight-right-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-toe-fourth': {
    field: 'abletobearweight-left-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-toe-fourth': {
    field: 'abletobearweight-right-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-toe-fifth': {
    field: 'abletobearweight-left-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-toe-fifth': {
    field: 'abletobearweight-right-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-wrist': {
    field: 'abletobearweight-left-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-wrist': {
    field: 'abletobearweight-right-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-forearm': {
    field: 'abletobearweight-left-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-forearm': {
    field: 'abletobearweight-right-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-elbow': {
    field: 'abletobearweight-left-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-elbow': {
    field: 'abletobearweight-right-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-upperarm': {
    field: 'abletobearweight-left-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-upperarm': {
    field: 'abletobearweight-right-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-shoulder': {
    field: 'abletobearweight-left-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-shoulder': {
    field: 'abletobearweight-right-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-knee': {
    field: 'abletobearweight-left-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-knee': {
    field: 'abletobearweight-right-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-lowerleg': {
    field: 'abletobearweight-left-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-lowerleg': {
    field: 'abletobearweight-right-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-left-ankle': {
    field: 'abletobearweight-left-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'abletobearweight-right-ankle': {
    field: 'abletobearweight-right-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-finger-index': {
    field: 'decreasedrom-left-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-finger-index': {
    field: 'decreasedrom-right-finger-index',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-finger-middle': {
    field: 'decreasedrom-left-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-finger-middle': {
    field: 'decreasedrom-right-finger-middle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-finger-ring': {
    field: 'decreasedrom-left-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-finger-ring': {
    field: 'decreasedrom-right-finger-ring',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-finger-little': {
    field: 'decreasedrom-left-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-finger-little': {
    field: 'decreasedrom-right-finger-little',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-finger-thumb': {
    field: 'decreasedrom-left-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-finger-thumb': {
    field: 'decreasedrom-right-finger-thumb',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-hand': {
    field: 'decreasedrom-left-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-hand': {
    field: 'decreasedrom-right-hand',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-foot': {
    field: 'decreasedrom-left-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-foot': {
    field: 'decreasedrom-right-foot',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-toe-great': {
    field: 'decreasedrom-left-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-toe-great': {
    field: 'decreasedrom-right-toe-great',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-toe-second': {
    field: 'decreasedrom-left-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-toe-second': {
    field: 'decreasedrom-right-toe-second',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-toe-third': {
    field: 'decreasedrom-left-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-toe-third': {
    field: 'decreasedrom-right-toe-third',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-toe-fourth': {
    field: 'decreasedrom-left-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-toe-fourth': {
    field: 'decreasedrom-right-toe-fourth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-toe-fifth': {
    field: 'decreasedrom-left-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-toe-fifth': {
    field: 'decreasedrom-right-toe-fifth',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-wrist': {
    field: 'decreasedrom-left-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-wrist': {
    field: 'decreasedrom-right-wrist',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-forearm': {
    field: 'decreasedrom-left-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-forearm': {
    field: 'decreasedrom-right-forearm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-elbow': {
    field: 'decreasedrom-left-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-elbow': {
    field: 'decreasedrom-right-elbow',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-upperarm': {
    field: 'decreasedrom-left-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-upperarm': {
    field: 'decreasedrom-right-upperarm',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-shoulder': {
    field: 'decreasedrom-left-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-shoulder': {
    field: 'decreasedrom-right-shoulder',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-knee': {
    field: 'decreasedrom-left-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-knee': {
    field: 'decreasedrom-right-knee',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-lowerleg': {
    field: 'decreasedrom-left-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-lowerleg': {
    field: 'decreasedrom-right-lowerleg',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-left-ankle': {
    field: 'decreasedrom-left-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  'decreasedrom-right-ankle': {
    field: 'decreasedrom-right-ankle',
    defaultValue: false,
    abnormal: true,
    group: 'form',
    card: 'musculoskeletal',
    label: '',
  },
  // >>> CARD = neurological
  // >> GROUP = normal
  'normal-mental-status': {
    field: 'normal-mental-status',
    defaultValue: true,
    abnormal: false,
    group: 'normal',
    card: 'neurological',
    label: 'Normal mental status',
  },
  // >>> CARD = psych
  // >> GROUP = normal
  'normal-affect': {
    field: 'normal-affect',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'psych',
    label: 'Normal affect',
  },
  'good-eye-contact': {
    field: 'good-eye-contact',
    defaultValue: false,
    abnormal: false,
    group: 'normal',
    card: 'psych',
    label: 'Good eye contact',
  },
  // >> GROUP = abnormal
  'depressed-affect': {
    field: 'depressed-affect',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'psych',
    label: 'Depressed affect',
  },
  'poor-eye-contact': {
    field: 'poor-eye-contact',
    defaultValue: false,
    abnormal: true,
    group: 'abnormal',
    card: 'psych',
    label: 'Poor eye contact',
  },
};

export const examObservationFieldsDetailsArray = Object.values(ExamObservationFieldsDetails);

export const rashesFields = examObservationFieldsDetailsArray
  .filter((details) => details.card === 'skin' && details.group === 'form')
  .map((details) => details.field);

export const rashesOptions = rashesFields.reduce(
  (previousValue, currentValue) => {
    previousValue[currentValue] = ExamObservationFieldsDetails[currentValue].label;
    return previousValue;
  },
  {} as Record<ExamFieldsNames, string>,
);

export const parseRashesFieldToName = (fieldName: string, fields: ExamObservationDTO[]): string => {
  const resultArr: string[] = [];

  resultArr.push(rashesOptions[fieldName as keyof typeof rashesOptions]);

  const field = fields.find((field) => field.field === fieldName)!;

  if (field.note) {
    resultArr.push(field.note);
  }

  return resultArr.join(' | ');
};

export const musculoskeletalFields: ExamFieldsNames[] = examObservationFieldsDetailsArray
  .filter((details) => details.card === 'musculoskeletal' && details.group === 'form')
  .map((details) => details.field);

export const musculoskeletalSideOptions = [
  {
    label: 'Left',
    value: 'left',
  },
  {
    label: 'Right',
    value: 'right',
  },
];

export const musculoskeletalBodyPartOptions = {
  finger: 'Finger',
  hand: 'Hand',
  wrist: 'Wrist',
  forearm: 'Forearm',
  elbow: 'Elbow',
  upperarm: 'Upper arm',
  shoulder: 'Shoulder',
  knee: 'Knee',
  lowerleg: 'Lower leg',
  ankle: 'Ankle',
  foot: 'Foot',
  toe: 'Toe',
};

export const musculoskeletalFingerOptions = {
  thumb: 'Thumb',
  index: 'Index',
  middle: 'Middle',
  ring: 'Ring',
  little: 'Little',
};

export const musculoskeletalToeOptions = {
  great: 'First',
  second: 'Second',
  third: 'Third',
  fourth: 'Fourth',
  fifth: 'Fifth',
};

export const musculoskeletalAbnormalOptions = {
  swelling: 'Swelling',
  deformity: 'Deformity',
  bruising: 'Bruising',
  abletobearweight: 'Able to bear weight',
  decreasedrom: 'Decreased ROM',
};

export const parseMusculoskeletalFieldToName = (field: string): string => {
  const arr = field.split('-');
  const resultArr: string[] = [];

  resultArr.push(musculoskeletalSideOptions.find((option) => option.value === arr[1])!.label);
  resultArr.push(musculoskeletalBodyPartOptions[arr[2] as keyof typeof musculoskeletalBodyPartOptions]);

  switch (arr[2]) {
    case 'finger':
      resultArr.push(musculoskeletalFingerOptions[arr[3] as keyof typeof musculoskeletalFingerOptions]);
      break;
    case 'toe':
      resultArr.push(musculoskeletalToeOptions[arr[3] as keyof typeof musculoskeletalToeOptions]);
      break;
  }

  resultArr.push(musculoskeletalAbnormalOptions[arr[0] as keyof typeof musculoskeletalAbnormalOptions]);

  return resultArr.join(' | ');
};
