export * from './helpers';

export interface Secrets {
  [secretName: string]: string;
}

export const getOptionalSecret = (secretKey: string, secrets: Secrets | null): string | undefined => {
  return secrets != null ? secrets[secretKey] : process.env[secretKey];
};

export const getSecret = (secretKey: string, secrets: Secrets | null): string => {
  const value = getOptionalSecret(secretKey, secrets);
  if (value == null) {
    throw new Error(`Secret or Environment Variable with key ${secretKey} was not set.`);
  }
  return value;
};

export enum SecretsKeys {
  AUTH0_ENDPOINT = 'AUTH0_ENDPOINT',
  AUTH0_CLIENT = 'AUTH0_CLIENT',
  AUTH0_SECRET = 'AUTH0_SECRET',
  AUTH0_AUDIENCE = 'AUTH0_AUDIENCE',
  DEFAULT_BILLING_RESOURCE = 'DEFAULT_BILLING_RESOURCE',
  FHIR_API = 'FHIR_API',
  PROJECT_API = 'PROJECT_API',
  PROJECT_ID = 'PROJECT_ID',
  ENVIRONMENT = 'ENVIRONMENT',
  SENDGRID_API_KEY = 'SENDGRID_API_KEY',
  SENDGRID_EMAIL_BCC = 'SENDGRID_EMAIL_BCC',
  IN_PERSON_SENDGRID_CONFIRMATION_EMAIL_TEMPLATE_ID = 'IN_PERSON_SENDGRID_CONFIRMATION_EMAIL_TEMPLATE_ID',
  IN_PERSON_SENDGRID_CANCELLATION_EMAIL_TEMPLATE_ID = 'IN_PERSON_SENDGRID_CANCELLATION_EMAIL_TEMPLATE_ID',
  IN_PERSON_SENDGRID_ERROR_EMAIL_TEMPLATE_ID = 'IN_PERSON_SENDGRID_ERROR_EMAIL_TEMPLATE_ID',
  ORGANIZATION_ID = 'ORGANIZATION_ID',
  BH_WEBSITE_URL = 'BH_WEBSITE_URL',
  WEBSITE_URL = 'WEBSITE_URL',
  MIXPANEL_TOKEN = 'MIXPANEL_TOKEN',
  IN_PERSON_PREBOOK_DISPLAY_TOMORROW_SLOTS_AT_HOUR = 'IN_PERSON_PREBOOK_DISPLAY_TOMORROW_SLOTS_AT_HOUR',
  IN_PERSON_PREVISIT_QUESTIONNAIRE = 'IN_PERSON_PREVISIT_QUESTIONNAIRE',
  VIRTUAL_PREVISIT_QUESTIONNAIRE = 'VIRTUAL_PREVISIT_QUESTIONNAIRE',

  VIRTUAL_SENDGRID_CONFIRMATION_EMAIL_TEMPLATE_ID = 'VIRTUAL_SENDGRID_CONFIRMATION_EMAIL_TEMPLATE_ID',
  VIRTUAL_SENDGRID_CANCELLATION_EMAIL_TEMPLATE_ID = 'VIRTUAL_SENDGRID_CANCELLATION_EMAIL_TEMPLATE_ID',
  VIRTUAL_SENDGRID_ERROR_EMAIL_TEMPLATE_ID = 'VIRTUAL_SENDGRID_ERROR_EMAIL_TEMPLATE_ID',
  VIRTUAL_SENDGRID_VIDEO_CHAT_INVITATION_EMAIL_TEMPLATE_ID = 'VIRTUAL_SENDGRID_VIDEO_CHAT_INVITATION_EMAIL_TEMPLATE_ID',

  FHIR_SCHEDULE_MEDICAID_ID = 'FHIR_SCHEDULE_MEDICAID_ID',
  FHIR_SCHEDULE_SELF_PAY_ID = 'FHIR_SCHEDULE_SELF_PAY_ID',
  FHIR_SCHEDULE_AETNA_ID = 'FHIR_SCHEDULE_AETNA_ID',
  FHIR_SCHEDULE_STAFF_ID = 'FHIR_SCHEDULE_STAFF_ID',
  CHANGE_CLIENT = 'CHANGE_CLIENT',
  CHANGE_SECRET = 'CHANGE_SECRET',
  CHANGE_API_BASE_URL = 'CHANGE_API_BASE_URL',
  CARDPOINTE_API_BASE_URL = 'CARDPOINTE_API_BASE_URL',
  CARDPOINTE_API_USERNAME = 'CARDPOINTE_API_USERNAME',
  CARDPOINTE_API_PASSWORD = 'CARDPOINTE_API_PASSWORD',
  SENDGRID_EMAIL_TEMPLATE_ID = 'SENDGRID_EMAIL_TEMPLATE_ID',
  SENDGRID_SPANISH_EMAIL_TEMPLATE_ID = 'SENDGRID_SPANISH_EMAIL_TEMPLATE_ID',
  SENDGRID_ERROR_EMAIL_TEMPLATE_ID = 'SENDGRID_ERROR_EMAIL_TEMPLATE_ID',
  CARDPOINTE_MERCHANT_ID_CT = 'CARDPOINTE_MERCHANT_ID_CT',
  CARDPOINTE_MERCHANT_ID_FL = 'CARDPOINTE_MERCHANT_ID_FL',
  CARDPOINTE_MERCHANT_ID_NC = 'CARDPOINTE_MERCHANT_ID_NC',
  CARDPOINTE_MERCHANT_ID_NJ = 'CARDPOINTE_MERCHANT_ID_NJ',
  CARDPOINTE_MERCHANT_ID_NY = 'CARDPOINTE_MERCHANT_ID_NY',
  CARDPOINTE_MERCHANT_ID_PA = 'CARDPOINTE_MERCHANT_ID_PA',
  CARDPOINTE_MERCHANT_ID_TX = 'CARDPOINTE_MERCHANT_ID_TX',
  S3_BUCKET_NAME = 'S3_BUCKET_NAME',
  S3_BUCKET_ACCESS_KEY = 'S3_BUCKET_ACCESS_KEY',
  S3_BUCKET_SECRET_ACCESS_KEY = 'S3_BUCKET_SECRET_ACCESS_KEY',
  IN_PERSON_SENDGRID_SPANISH_CANCELLATION_EMAIL_TEMPLATE_ID = 'IN_PERSON_SENDGRID_SPANISH_CANCELLATION_EMAIL_TEMPLATE_ID',
  IN_PERSON_SENDGRID_SPANISH_CONFIRMATION_EMAIL_TEMPLATE_ID = 'IN_PERSON_SENDGRID_SPANISH_CONFIRMATION_EMAIL_TEMPLATE_ID',
  IN_PERSON_SENDGRID_ISSUE_REPORT_EMAIL_TEMPLATE_ID = 'IN_PERSON_SENDGRID_ISSUE_REPORT_EMAIL_TEMPLATE_ID',
  INTAKE_ISSUE_REPORT_EMAIL_GROUP_ID = 'INTAKE_ISSUE_REPORT_EMAIL_GROUP_ID',
  NLM_API_KEY = 'NLM_API_KEY',
  CANDID_CLIENT_ID = 'CANDID_CLIENT_ID',
  CANDID_CLIENT_SECRET = 'CANDID_CLIENT_SECRET',
  CANDID_ENV = 'CANDID_ENV',
}
