/* eslint-disable @typescript-eslint/explicit-function-return-type */
const FHIR_API_URL = 'https://testing.fhir-api.zapehr.com';
const PROJECT_API_URL = 'http://localhost:todo';
const UPLOAD_URL = 'https://testing.project-api.zapehr.com/v1';

module.exports = {
  PORT: 3001,
  REACT_APP_FHIR_API_URL: FHIR_API_URL,
  REACT_APP_PROJECT_API_URL: PROJECT_API_URL,
  REACT_APP_UPLOAD_URL: UPLOAD_URL,
  REACT_APP_CHECK_IN_ZAMBDA_ID: 'todo',
  REACT_APP_CREATE_APPOINTMENT_ZAMBDA_ID: 'todo',
  REACT_APP_CANCEL_APPOINTMENT_ZAMBDA_ID: 'todo',
  REACT_APP_GET_PATIENTS_ZAMBDA_ID: 'todo',
  REACT_APP_UPDATE_APPOINTMENT_ZAMBDA_ID: 'todo',
  REACT_APP_GET_SLOTS_AVAILABILITY_ZAMBDA_ID: 'todo',
  REACT_APP_GET_LOCATIONS_ZAMBDA_ID: 'todo',
  REACT_APP_GET_APPOINTMENTS_ZAMBDA_ID: 'todo',
  REACT_APP_UPDATE_PAPERWORK_ZAMBDA_ID: 'todo',
  REACT_APP_CHECK_PAPERWORK_STATUS_ZAMBDA_ID: 'todo',
  REACT_APP_MIXPANEL_TOKEN: 'todo',
};
