/* eslint-disable @typescript-eslint/explicit-function-return-type */
const FHIR_API_URL = 'https://testing.fhir-api.zapehr.com';
const PROJECT_API_URL = 'https://testing.project-api.zapehr.com/v1';
const CREATE_APPOINTMENT_ZAMBDA_ID = 'todo';
const UPDATE_APPOINTMENT_ZAMBDA_ID = 'todo';
const UPDATE_PAPERWORK_ZAMBDA_ID = 'todo';

module.exports = {
  PORT: 3001,
  REACT_APP_FHIR_API_URL: FHIR_API_URL,
  REACT_APP_PROJECT_API_URL: PROJECT_API_URL,
  REACT_APP_UPLOAD_URL: PROJECT_API_URL,
  REACT_APP_CREATE_APPOINTMENT_ZAMBDA_ID: CREATE_APPOINTMENT_ZAMBDA_ID,
  REACT_APP_UPDATE_APPOINTMENT_ZAMBDA_ID: UPDATE_APPOINTMENT_ZAMBDA_ID,
  REACT_APP_UPDATE_PAPERWORK_ZAMBDA_ID: UPDATE_PAPERWORK_ZAMBDA_ID,
};
