import * as fs from 'fs';
import * as path from 'path';
import * as prettier from 'prettier';
import { parseX12CodeList } from 'utils/lib/types/data/billing/x12-code-list';

// Renders the CARC and RARC tables the billing app offers when a biller keys in a paper remit, from
// the lists copied off x12.org (Current filter) into scripts/data/x12/. Run via `npm run codes:x12`
// after replacing a list; a unit test in utils (x12-code-list.test.ts) fails when a committed table
// no longer matches its source list.

const SOURCE_DIR = path.resolve(__dirname, 'data/x12');
const TARGET_DIR = path.resolve(__dirname, '../packages/utils/lib/types/data/billing');

const LISTS = [
  {
    source: 'carc-list.txt',
    target: 'carc-codes.generated.ts',
    exportName: 'CARC_CODE_LIST',
    title: 'X12 Claim Adjustment Reason Codes (CARC, external code list 139)',
    lastUpdated: '11/1/2025',
    dropUsage: true,
  },
  {
    source: 'rarc-list.txt',
    target: 'rarc-codes.generated.ts',
    exportName: 'RARC_CODE_LIST',
    title: 'X12 Remittance Advice Remark Codes (RARC, external code list 411)',
    lastUpdated: '7/1/2026',
    dropUsage: false,
  },
];

async function main(): Promise<void> {
  for (const list of LISTS) {
    const entries = parseX12CodeList(fs.readFileSync(path.join(SOURCE_DIR, list.source), 'utf-8'), {
      dropUsage: list.dropUsage,
    });
    const source = [
      `// ${list.title}, current codes only, as published by X12 (last updated ${list.lastUpdated}).`,
      `// Generated by \`npm run codes:x12\` from scripts/data/x12/${list.source} — do not edit by hand.`,
      `import type { X12CodeListEntry } from './x12-code-list';`,
      '',
      `export const ${list.exportName}: readonly X12CodeListEntry[] = [`,
      ...entries.map(
        (entry) => `  { code: ${JSON.stringify(entry.code)}, description: ${JSON.stringify(entry.description)} },`
      ),
      '];',
      '',
    ].join('\n');
    const target = path.join(TARGET_DIR, list.target);
    const config = await prettier.resolveConfig(target);
    fs.writeFileSync(target, await prettier.format(source, { ...config, parser: 'typescript' }));
    console.log(`Wrote ${entries.length} codes to ${target}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
