import * as fs from 'fs';
import * as path from 'path';
import * as prettier from 'prettier';
import { parseRemitCodeCsv, RemitCodeLists } from 'utils/lib/types/data/billing/remit-codes';

// Renders the CARC and RARC tables the billing app offers when a biller keys in a paper remit, from
// scripts/data/remit-codes.csv (one row per code, with the plain-language label billers see). Run via
// `npm run codes:remit` after editing the CSV; a unit test in utils (remit-codes.test.ts) fails when
// a committed table no longer matches it.

const SOURCE = path.resolve(__dirname, 'data/remit-codes.csv');
const TARGET_DIR = path.resolve(__dirname, '../packages/utils/lib/types/data/billing');

const TABLES: { list: keyof RemitCodeLists; target: string; exportName: string; title: string }[] = [
  {
    list: 'carc',
    target: 'carc-codes.generated.ts',
    exportName: 'CARC_CODE_LIST',
    title: 'Claim adjustment reason codes (CARCs)',
  },
  {
    list: 'rarc',
    target: 'rarc-codes.generated.ts',
    exportName: 'RARC_CODE_LIST',
    title: 'Remittance advice remark codes (RARCs)',
  },
];

async function main(): Promise<void> {
  const lists = parseRemitCodeCsv(fs.readFileSync(SOURCE, 'utf-8'));
  for (const table of TABLES) {
    const entries = lists[table.list];
    const source = [
      `// ${table.title} billers can pick when keying in a remit, in code order.`,
      '// Generated by `npm run codes:remit` from scripts/data/remit-codes.csv — do not edit by hand.',
      `import type { RemitCodeEntry } from './remit-codes';`,
      '',
      `export const ${table.exportName}: readonly RemitCodeEntry[] = [`,
      ...entries.map(
        (entry) => `  { code: ${JSON.stringify(entry.code)}, description: ${JSON.stringify(entry.description)} },`
      ),
      '];',
      '',
    ].join('\n');
    const target = path.join(TARGET_DIR, table.target);
    const config = await prettier.resolveConfig(target);
    fs.writeFileSync(target, await prettier.format(source, { ...config, parser: 'typescript' }));
    console.log(`Wrote ${entries.length} codes to ${target}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
