import Oystehr from '@oystehr/sdk';
import { randomUUID } from 'crypto';
import { DocumentReference } from 'fhir/r4b';
import { DateTime } from 'luxon';
import { StandardFonts } from 'pdf-lib';
import {
  BUCKET_NAMES,
  createFilesDocumentReferences,
  EXTERNAL_LAB_LABEL_PDF_BASE_NAME,
  EXTERNAL_LAB_LABEL_PDF_DOC_REF_DOCTYPE,
  EXTERNAL_LAB_LABEL_XML_DOC_REF_DOCTYPE,
  getPresignedURL,
  LabelConfig,
  MIME_TYPES,
  Secrets,
} from 'utils';
import { makeZ3Url } from './../presigned-file-urls';
import { createPresignedUrl, uploadObjectToZ3 } from './../z3Utils';
import { getLabListResource } from './lab-pdf-utils';
import { Y_POS_GAP as pdfClientGapSubtraction } from './pdf-consts';
import { createPdfClient, PdfInfo } from './pdf-utils';
import { PdfClientStyles, TextStyle } from './types';

interface ExternalLabsLabelContent {
  patientLastName: string;
  patientFirstName: string;
  patientId: string;
  patientDateOfBirth: DateTime | undefined;
  sampleCollectionDateAndTimezone: { sampleCollectionDate: DateTime; timezone: string | undefined } | undefined;
  accountNumber: string; // this is the lab provided account number. Same one used to submit the order
  orderNumber: string; // number generated by oystehr submit labs on order submit
}

export interface ExternalLabsLabelConfig {
  labelConfig: LabelConfig;
  content: ExternalLabsLabelContent;
}

export const convertLabeConfigToPdfClientStyles = (labelConfig: LabelConfig): PdfClientStyles => {
  const inchesToPoints = (sizeInches: number): number => {
    // conversion factor is 1 point = 1/72 inches.
    // pdf-lib uses Points not pixels
    return sizeInches * 72;
  };

  const pdfClientStyles: PdfClientStyles = {
    initialPage: {
      width: inchesToPoints(labelConfig.widthInches),
      height: inchesToPoints(labelConfig.heightInches),
      pageMargins: {
        left: inchesToPoints(labelConfig.marginLeftInches),
        right: inchesToPoints(labelConfig.marginRightInches),
        top: inchesToPoints(labelConfig.marginTopInches),
        bottom: inchesToPoints(labelConfig.marginBottomInches),
      },
    },
  };

  return pdfClientStyles;
};

const createExternalLabsLabelPdfBytes = async (data: ExternalLabsLabelConfig): Promise<Uint8Array> => {
  const { labelConfig, content } = data;

  const pdfClientStyles = convertLabeConfigToPdfClientStyles(labelConfig);

  const pdfClient = await createPdfClient(pdfClientStyles);
  // the pdf client initializes YPos to some non-zero number and it's causing huge gaps
  pdfClient.setY(pdfClient.getY() + pdfClientGapSubtraction - 15);

  const CourierBold = await pdfClient.embedStandardFont(StandardFonts.CourierBold);
  const Courier = await pdfClient.embedStandardFont(StandardFonts.Courier);

  const baseFontSize = 7;
  const baseSpacing = 2;

  const textStyles: Record<string, TextStyle> = {
    fieldText: {
      fontSize: baseFontSize,
      spacing: baseSpacing,
      font: Courier,
      newLineAfter: false,
    },
    fieldTextBold: {
      fontSize: baseFontSize,
      spacing: baseSpacing,
      font: CourierBold,
      newLineAfter: false,
    },
    fieldHeader: {
      fontSize: baseFontSize,
      font: CourierBold,
      spacing: baseSpacing,
    },
  };

  const NEWLINE_Y_DROP =
    pdfClient.getTextDimensions('Any text used to get height', textStyles.fieldHeader).height + baseSpacing;

  interface Column {
    header?: string;
    value: string;
  }

  // const columnGapPoints = pdfClientStyles.initialPage.width / 30;
  const columnGapPoints = 0.0125;
  const rightColumnXStart = pdfClientStyles.initialPage.width / 2 + columnGapPoints / 2;

  const drawHeaderAndInlineText = (header: string, text: string): void => {
    pdfClient.drawTextSequential(`${header}: `, textStyles.fieldHeader);
    pdfClient.drawTextSequential(text, textStyles.fieldTextBold);
  };

  const drawColumnRowAndNewline = (leftColumn: Column, rightColumn: Column): void => {
    const leftHeader = leftColumn.header ? `${leftColumn.header}: ` : '';

    let startXPos = pdfClient.getLeftBound();
    startXPos = pdfClient.drawStartXPosSpecifiedText(leftHeader, textStyles.fieldHeader, startXPos).endXPos;
    pdfClient.drawStartXPosSpecifiedText(leftColumn.value, textStyles.fieldTextBold, startXPos);

    // now start the right column
    pdfClient.setX(rightColumnXStart);

    const rightHeader = rightColumn.header ? `${rightColumn.header}: ` : '';

    startXPos = pdfClient.drawStartXPosSpecifiedText(rightHeader, textStyles.fieldHeader, pdfClient.getX()).endXPos;
    pdfClient.drawStartXPosSpecifiedText(rightColumn.value, textStyles.fieldTextBold, startXPos);
    pdfClient.newLine(NEWLINE_Y_DROP);
  };

  // now we actually draw the label
  /* 
  Patient last name, first name
  PID
  DOB (in one column)       Collection date (in the next column)
  Account number            
  Requisition number (aka order number)
  */
  const {
    patientLastName,
    patientFirstName,
    patientId,
    patientDateOfBirth,
    sampleCollectionDateAndTimezone,
    accountNumber,
    orderNumber,
  } = content;

  pdfClient.drawTextSequential(`${patientLastName}, ${patientFirstName}`, {
    ...textStyles.fieldHeader,
    fontSize: textStyles.fieldHeader.fontSize + 1,
  });
  pdfClient.newLine(NEWLINE_Y_DROP);

  drawHeaderAndInlineText('PID', patientId);
  pdfClient.newLine(NEWLINE_Y_DROP);

  drawColumnRowAndNewline(
    { header: 'DOB', value: getPatientDOBForLabelDisplay(patientDateOfBirth) },
    { header: 'Coll', value: getSampleCollectionTimestampForLabelDisplay(sampleCollectionDateAndTimezone) }
  );

  drawHeaderAndInlineText('Acct #', accountNumber);
  pdfClient.newLine(NEWLINE_Y_DROP);

  drawHeaderAndInlineText('Req #', orderNumber);
  pdfClient.newLine(NEWLINE_Y_DROP);

  return await pdfClient.save();
};

const getPatientDOBForLabelDisplay = (dob: DateTime | undefined): string => {
  return dob ? dob.toFormat('MM/dd/yyyy') : '';
};

const getSampleCollectionTimestampForLabelDisplay = (
  sampleCollectionDateAndTimezone:
    | {
        sampleCollectionDate: DateTime;
        timezone: string | undefined;
      }
    | undefined
): string => {
  const sampleCollectionDate = sampleCollectionDateAndTimezone?.sampleCollectionDate;
  const timezone = sampleCollectionDateAndTimezone?.timezone;
  console.log('for sampleCollectionDate, this is timestamp and timezone', sampleCollectionDate?.toISO(), timezone);

  const zonedSampleCollectionDate =
    timezone && sampleCollectionDate ? sampleCollectionDate.setZone(timezone) : sampleCollectionDate;

  return zonedSampleCollectionDate ? zonedSampleCollectionDate.toFormat('MM/dd/yyyy') : '';
};

async function createExternalLabsLabelPDFHelper(
  input: ExternalLabsLabelConfig,
  secrets: Secrets | null,
  token: string
): Promise<PdfInfo> {
  console.log('Creating external labs label pdf bytes');

  const pdfBytes = await createExternalLabsLabelPdfBytes(input).catch((error) => {
    throw new Error('failed creating external labs label pdfBytes: ' + error.message);
  });

  console.log(`Created external labs label pdf bytes`);

  const fileName = `${EXTERNAL_LAB_LABEL_PDF_BASE_NAME}-${input.content.orderNumber}.pdf`;

  console.log(`Creating base file url for file ${fileName}`);

  const baseFileUrl = makeZ3Url({
    secrets,
    fileName,
    bucketName: BUCKET_NAMES.LABS,
    patientID: input.content.patientId,
  });

  console.log('Uploading file to bucket, ', BUCKET_NAMES.LABS);

  try {
    const presignedUrl = await createPresignedUrl(token, baseFileUrl, 'upload');
    await uploadObjectToZ3(pdfBytes, presignedUrl);
  } catch (error: any) {
    throw new Error(`failed uploading pdf ${fileName} to z3:  ${JSON.stringify(error.message)}`);
  }

  // for testing
  // savePdfLocally(pdfBytes);

  return { title: fileName, uploadURL: baseFileUrl };
}

// this is what should get called in submit-lab-order / update-lab-order-resources
export async function createExternalLabLabelResources(
  labelConfig: ExternalLabsLabelConfig,
  encounterId: string,
  serviceRequestID: string,
  secrets: Secrets | null,
  token: string,
  oystehr: Oystehr
): Promise<{
  labelPdf: { docRef: DocumentReference; presignedURL: string };
  labelXml: { docRef: DocumentReference; presignedURL: string };
}> {
  const [labelPdf, labelXml] = await Promise.all([
    createExternalLabsLabelPDF(labelConfig, encounterId, serviceRequestID, secrets, token, oystehr),
    createExternalLabsLabelXML(labelConfig, encounterId, serviceRequestID, secrets, token, oystehr),
  ]);

  return { labelPdf, labelXml };
}

async function createExternalLabsLabelPDF(
  labelConfig: ExternalLabsLabelConfig,
  encounterId: string,
  serviceRequestID: string,
  secrets: Secrets | null,
  token: string,
  oystehr: Oystehr
): Promise<{ docRef: DocumentReference; presignedURL: string }> {
  const pdfInfo = await createExternalLabsLabelPDFHelper(labelConfig, secrets, token);

  console.log(`This is the made pdfInfo`, JSON.stringify(pdfInfo));

  const labListResource = await getLabListResource(oystehr, labelConfig.content.patientId, secrets, pdfInfo.title);

  const { docRefs } = await createFilesDocumentReferences({
    files: [{ url: pdfInfo.uploadURL, title: pdfInfo.title }],
    type: { coding: [EXTERNAL_LAB_LABEL_PDF_DOC_REF_DOCTYPE], text: 'External lab sample label' },
    references: {
      subject: {
        reference: `Patient/${labelConfig.content.patientId}`,
      },
      context: {
        related: [
          {
            reference: `ServiceRequest/${serviceRequestID}`,
          },
        ],
        encounter: [{ reference: `Encounter/${encounterId}` }],
      },
    },
    docStatus: 'final',
    dateCreated: DateTime.now().setZone('UTC').toISO() ?? '',
    oystehr,
    searchParams: [{ name: 'related', value: `ServiceRequest/${serviceRequestID}` }],
    generateUUID: randomUUID,
    listResources: labListResource ? [labListResource] : [], // this for whatever reason needs to get added otherwise the function never adds the new docRef to the returned array
  });

  console.log(`These are the docRefs returned for the label: `, JSON.stringify(docRefs));

  if (!docRefs.length) {
    throw new Error('Unable to make docRefs for label');
  }

  const presignedURL = await getPresignedURL(pdfInfo.uploadURL, token);

  if (!presignedURL) {
    throw new Error('Failed to get presigned URL for External lab label PDF');
  }

  return { docRef: docRefs[0], presignedURL };
}

async function createExternalLabsLabelXML(
  labelConfig: ExternalLabsLabelConfig,
  encounterId: string,
  serviceRequestID: string,
  secrets: Secrets | null,
  token: string,
  oystehr: Oystehr
): Promise<{ docRef: DocumentReference; presignedURL: string }> {
  const xmlString = createLabelXMLString(labelConfig.content);

  console.log(`This is the xmlString`, xmlString);

  const fileName = `${EXTERNAL_LAB_LABEL_PDF_BASE_NAME}-${labelConfig.content.orderNumber}.xml`;

  console.log(`Creating base file url for file ${fileName}`);

  const baseFileUrl = makeZ3Url({
    secrets,
    fileName,
    bucketName: BUCKET_NAMES.LABS,
    patientID: labelConfig.content.patientId,
  });

  console.log('Uploading file to bucket, ', BUCKET_NAMES.LABS);
  const encoder = new TextEncoder();
  const xmlStringAsUint8Array = encoder.encode(xmlString);

  try {
    const uploadPresignedUrl = await createPresignedUrl(token, baseFileUrl, 'upload');
    await uploadObjectToZ3(xmlStringAsUint8Array, uploadPresignedUrl, MIME_TYPES.XML);
  } catch (error: any) {
    throw new Error(`failed uploading xml label ${fileName} to z3:  ${JSON.stringify(error.message)}`);
  }
  console.log('Successfully uploaded xml label file', baseFileUrl);

  const labListResource = await getLabListResource(oystehr, labelConfig.content.patientId, secrets, fileName);

  const { docRefs } = await createFilesDocumentReferences({
    files: [{ url: baseFileUrl, title: fileName }],
    type: { coding: [EXTERNAL_LAB_LABEL_XML_DOC_REF_DOCTYPE], text: 'External lab sample label xml' },
    references: {
      subject: {
        reference: `Patient/${labelConfig.content.patientId}`,
      },
      context: {
        related: [
          {
            reference: `ServiceRequest/${serviceRequestID}`,
          },
        ],
        encounter: [{ reference: `Encounter/${encounterId}` }],
      },
    },
    docStatus: 'final',
    dateCreated: DateTime.now().setZone('UTC').toISO() ?? '',
    oystehr,
    searchParams: [{ name: 'related', value: `ServiceRequest/${serviceRequestID}` }],
    generateUUID: randomUUID,
    listResources: labListResource ? [labListResource] : [], // this for whatever reason needs to get added otherwise the function never adds the new docRef to the returned array
  });

  console.log(`These are the docRefs returned for the xml label: `, JSON.stringify(docRefs));

  if (!docRefs.length) {
    throw new Error('Unable to make docRefs for xml label');
  }

  const presignedURL = await getPresignedURL(baseFileUrl, token);

  if (!presignedURL) {
    throw new Error('Failed to get presigned URL for External lab label xml');
  }

  return { docRef: docRefs[0], presignedURL };
}

// LABS TODO: get rid of this version once we have the friendly pid. This puts the PID on two lines to avoid truncating
const createLabelXMLString = (content: ExternalLabsLabelContent): string => {
  return `
  <?xml version="1.0" encoding="utf-8"?>
<DesktopLabel Version="1">
  <DYMOLabel Version="4">
    <Description>DYMO Label</Description>
    <Orientation>Portrait</Orientation>
    <LabelName>Small30334</LabelName>
    <InitialLength>0</InitialLength>
    <BorderStyle>SolidLine</BorderStyle>
    <DYMORect>
      <DYMOPoint>
        <X>0.039999966</X>
        <Y>0.060000002</Y>
      </DYMOPoint>
      <Size>
        <Width>2.17</Width>
        <Height>1.13</Height>
      </Size>
    </DYMORect>
    <BorderColor>
      <SolidColorBrush>
        <Color A="1" R="0" G="0" B="0"></Color>
      </SolidColorBrush>
    </BorderColor>
    <BorderThickness>1</BorderThickness>
    <Show_Border>False</Show_Border>
    <HasFixedLength>False</HasFixedLength>
    <FixedLengthValue>0</FixedLengthValue>
    <DynamicLayoutManager>
      <RotationBehavior>ClearObjects</RotationBehavior>
      <LabelObjects>
        <TextObject>
          <Name>Patient Name</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>${content.patientLastName}, ${content.patientFirstName}</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>9</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>0.03999997</X>
              <Y>0.09090942</Y>
            </DYMOPoint>
            <Size>
              <Width>2.04938</Width>
              <Height>0.22315212</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
        <TextObject>
          <Name>Patient ID Line One</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>PID:</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>7</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>0.04000002</X>
              <Y>0.28714654</Y>
            </DYMOPoint>
            <Size>
              <Width>2.0558572</Width>
              <Height>0.1467135</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
        <TextObject>
          <Name>Patient ID Line Two</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>${content.patientId}</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>7</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>0.040000025</X>
              <Y>0.43386006</Y>
            </DYMOPoint>
            <Size>
              <Width>2.1700017</Width>
              <Height>0.125</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
        <TextObject>
          <Name>DOB</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>DOB: ${getPatientDOBForLabelDisplay(content.patientDateOfBirth)}</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>7</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>0.039999858</X>
              <Y>0.55886006</Y>
            </DYMOPoint>
            <Size>
              <Width>1.0206192</Width>
              <Height>0.13361889</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
        <TextObject>
          <Name>Collected</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>Coll: ${getSampleCollectionTimestampForLabelDisplay(
                  content.sampleCollectionDateAndTimezone
                )}</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>7</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>1.1249998</X>
              <Y>0.5556941</Y>
            </DYMOPoint>
            <Size>
              <Width>1.085</Width>
              <Height>0.13704132</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
        <TextObject>
          <Name>Account</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>Acct #: ${content.accountNumber}</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>7</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
            <LineTextSpan />
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>0.039999858</X>
              <Y>0.69273555</Y>
            </DYMOPoint>
            <Size>
              <Width>2.0579083</Width>
              <Height>0.13794978</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
        <TextObject>
          <Name>Order</Name>
          <Brushes>
            <BackgroundBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BackgroundBrush>
            <BorderBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </BorderBrush>
            <StrokeBrush>
              <SolidColorBrush>
                <Color A="1" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </StrokeBrush>
            <FillBrush>
              <SolidColorBrush>
                <Color A="0" R="0" G="0" B="0"></Color>
              </SolidColorBrush>
            </FillBrush>
          </Brushes>
          <Rotation>Rotation0</Rotation>
          <OutlineThickness>1</OutlineThickness>
          <IsOutlined>False</IsOutlined>
          <BorderStyle>SolidLine</BorderStyle>
          <Margin>
            <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
          </Margin>
          <HorizontalAlignment>Left</HorizontalAlignment>
          <VerticalAlignment>Middle</VerticalAlignment>
          <FitMode>None</FitMode>
          <IsVertical>False</IsVertical>
          <FormattedText>
            <FitMode>None</FitMode>
            <HorizontalAlignment>Left</HorizontalAlignment>
            <VerticalAlignment>Middle</VerticalAlignment>
            <IsVertical>False</IsVertical>
            <LineTextSpan>
              <TextSpan>
                <Text>Order #: ${content.orderNumber}</Text>
                <FontInfo>
                  <FontName>Courier New</FontName>
                  <FontSize>7</FontSize>
                  <IsBold>True</IsBold>
                  <IsItalic>False</IsItalic>
                  <IsUnderline>False</IsUnderline>
                  <FontBrush>
                    <SolidColorBrush>
                      <Color A="1" R="0" G="0" B="0"></Color>
                    </SolidColorBrush>
                  </FontBrush>
                </FontInfo>
              </TextSpan>
            </LineTextSpan>
          </FormattedText>
          <ObjectLayout>
            <DYMOPoint>
              <X>0.039999858</X>
              <Y>0.832853</Y>
            </DYMOPoint>
            <Size>
              <Width>2.1201644</Width>
              <Height>0.13289689</Height>
            </Size>
          </ObjectLayout>
        </TextObject>
      </LabelObjects>
    </DynamicLayoutManager>
  </DYMOLabel>
  <LabelApplication>Blank</LabelApplication>
  <DataTable>
    <Columns></Columns>
    <Rows></Rows>
  </DataTable>
</DesktopLabel>`;
};

// This is effectively the template for the xml label
// for paper type Small 30334
// This puts pid on one line for niceness but will truncate long uuid pids
// LABS TODO: USE THIS FUNCTION ONCE WE USE THE SHORT FRIENDLY PID
// const createLabelXMLString = (content: ExternalLabsLabelContent): string => {
//   return `<?xml version="1.0" encoding="utf-8"?>
// <DesktopLabel Version="1">
//   <DYMOLabel Version="4">
//     <Description>DYMO Label</Description>
//     <Orientation>Portrait</Orientation>
//     <LabelName>Small30334</LabelName>
//     <InitialLength>0</InitialLength>
//     <BorderStyle>SolidLine</BorderStyle>
//     <DYMORect>
//       <DYMOPoint>
//         <X>0.039999966</X>
//         <Y>0.060000002</Y>
//       </DYMOPoint>
//       <Size>
//         <Width>2.17</Width>
//         <Height>1.13</Height>
//       </Size>
//     </DYMORect>
//     <BorderColor>
//       <SolidColorBrush>
//         <Color A="1" R="0" G="0" B="0"></Color>
//       </SolidColorBrush>
//     </BorderColor>
//     <BorderThickness>1</BorderThickness>
//     <Show_Border>False</Show_Border>
//     <HasFixedLength>False</HasFixedLength>
//     <FixedLengthValue>0</FixedLengthValue>
//     <DynamicLayoutManager>
//       <RotationBehavior>ClearObjects</RotationBehavior>
//       <LabelObjects>
//         <TextObject>
//           <Name>Patient Name</Name>
//           <Brushes>
//             <BackgroundBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BackgroundBrush>
//             <BorderBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BorderBrush>
//             <StrokeBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </StrokeBrush>
//             <FillBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </FillBrush>
//           </Brushes>
//           <Rotation>Rotation0</Rotation>
//           <OutlineThickness>1</OutlineThickness>
//           <IsOutlined>False</IsOutlined>
//           <BorderStyle>SolidLine</BorderStyle>
//           <Margin>
//             <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
//           </Margin>
//           <HorizontalAlignment>Left</HorizontalAlignment>
//           <VerticalAlignment>Middle</VerticalAlignment>
//           <FitMode>None</FitMode>
//           <IsVertical>False</IsVertical>
//           <FormattedText>
//             <FitMode>None</FitMode>
//             <HorizontalAlignment>Left</HorizontalAlignment>
//             <VerticalAlignment>Middle</VerticalAlignment>
//             <IsVertical>False</IsVertical>
//             <LineTextSpan>
//               <TextSpan>
//                 <Text>${content.patientLastName}, ${content.patientFirstName}</Text>
//                 <FontInfo>
//                   <FontName>Courier New</FontName>
//                   <FontSize>9</FontSize>
//                   <IsBold>True</IsBold>
//                   <IsItalic>False</IsItalic>
//                   <IsUnderline>False</IsUnderline>
//                   <FontBrush>
//                     <SolidColorBrush>
//                       <Color A="1" R="0" G="0" B="0"></Color>
//                     </SolidColorBrush>
//                   </FontBrush>
//                 </FontInfo>
//               </TextSpan>
//             </LineTextSpan>
//           </FormattedText>
//           <ObjectLayout>
//             <DYMOPoint>
//               <X>0.03999997</X>
//               <Y>0.09090942</Y>
//             </DYMOPoint>
//             <Size>
//               <Width>2.04938</Width>
//               <Height>0.22315212</Height>
//             </Size>
//           </ObjectLayout>
//         </TextObject>
//         <TextObject>
//           <Name>Patient ID</Name>
//           <Brushes>
//             <BackgroundBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BackgroundBrush>
//             <BorderBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BorderBrush>
//             <StrokeBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </StrokeBrush>
//             <FillBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </FillBrush>
//           </Brushes>
//           <Rotation>Rotation0</Rotation>
//           <OutlineThickness>1</OutlineThickness>
//           <IsOutlined>False</IsOutlined>
//           <BorderStyle>SolidLine</BorderStyle>
//           <Margin>
//             <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
//           </Margin>
//           <HorizontalAlignment>Left</HorizontalAlignment>
//           <VerticalAlignment>Middle</VerticalAlignment>
//           <FitMode>None</FitMode>
//           <IsVertical>False</IsVertical>
//           <FormattedText>
//             <FitMode>None</FitMode>
//             <HorizontalAlignment>Left</HorizontalAlignment>
//             <VerticalAlignment>Middle</VerticalAlignment>
//             <IsVertical>False</IsVertical>
//             <LineTextSpan>
//               <TextSpan>
//                 <Text>PID: ${content.patientId}</Text>
//                 <FontInfo>
//                   <FontName>Courier New</FontName>
//                   <FontSize>7</FontSize>
//                   <IsBold>True</IsBold>
//                   <IsItalic>False</IsItalic>
//                   <IsUnderline>False</IsUnderline>
//                   <FontBrush>
//                     <SolidColorBrush>
//                       <Color A="1" R="0" G="0" B="0"></Color>
//                     </SolidColorBrush>
//                   </FontBrush>
//                 </FontInfo>
//               </TextSpan>
//             </LineTextSpan>
//           </FormattedText>
//           <ObjectLayout>
//             <DYMOPoint>
//               <X>0.04000002</X>
//               <Y>0.28714654</Y>
//             </DYMOPoint>
//             <Size>
//               <Width>2.0558572</Width>
//               <Height>0.1467135</Height>
//             </Size>
//           </ObjectLayout>
//         </TextObject>
//         <TextObject>
//           <Name>DOB</Name>
//           <Brushes>
//             <BackgroundBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BackgroundBrush>
//             <BorderBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BorderBrush>
//             <StrokeBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </StrokeBrush>
//             <FillBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </FillBrush>
//           </Brushes>
//           <Rotation>Rotation0</Rotation>
//           <OutlineThickness>1</OutlineThickness>
//           <IsOutlined>False</IsOutlined>
//           <BorderStyle>SolidLine</BorderStyle>
//           <Margin>
//             <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
//           </Margin>
//           <HorizontalAlignment>Left</HorizontalAlignment>
//           <VerticalAlignment>Middle</VerticalAlignment>
//           <FitMode>None</FitMode>
//           <IsVertical>False</IsVertical>
//           <FormattedText>
//             <FitMode>None</FitMode>
//             <HorizontalAlignment>Left</HorizontalAlignment>
//             <VerticalAlignment>Middle</VerticalAlignment>
//             <IsVertical>False</IsVertical>
//             <LineTextSpan>
//               <TextSpan>
//                 <Text>DOB: ${getPatientDOBForLabelDisplay(content.patientDateOfBirth)}</Text>
//                 <FontInfo>
//                   <FontName>Courier New</FontName>
//                   <FontSize>7</FontSize>
//                   <IsBold>True</IsBold>
//                   <IsItalic>False</IsItalic>
//                   <IsUnderline>False</IsUnderline>
//                   <FontBrush>
//                     <SolidColorBrush>
//                       <Color A="1" R="0" G="0" B="0"></Color>
//                     </SolidColorBrush>
//                   </FontBrush>
//                 </FontInfo>
//               </TextSpan>
//             </LineTextSpan>
//           </FormattedText>
//           <ObjectLayout>
//             <DYMOPoint>
//               <X>0.04000002</X>
//               <Y>0.43386003</Y>
//             </DYMOPoint>
//             <Size>
//               <Width>1.0206192</Width>
//               <Height>0.13361889</Height>
//             </Size>
//           </ObjectLayout>
//         </TextObject>
//         <TextObject>
//           <Name>Collected</Name>
//           <Brushes>
//             <BackgroundBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BackgroundBrush>
//             <BorderBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BorderBrush>
//             <StrokeBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </StrokeBrush>
//             <FillBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </FillBrush>
//           </Brushes>
//           <Rotation>Rotation0</Rotation>
//           <OutlineThickness>1</OutlineThickness>
//           <IsOutlined>False</IsOutlined>
//           <BorderStyle>SolidLine</BorderStyle>
//           <Margin>
//             <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
//           </Margin>
//           <HorizontalAlignment>Left</HorizontalAlignment>
//           <VerticalAlignment>Middle</VerticalAlignment>
//           <FitMode>None</FitMode>
//           <IsVertical>False</IsVertical>
//           <FormattedText>
//             <FitMode>None</FitMode>
//             <HorizontalAlignment>Left</HorizontalAlignment>
//             <VerticalAlignment>Middle</VerticalAlignment>
//             <IsVertical>False</IsVertical>
//             <LineTextSpan>
//               <TextSpan>
//                 <Text>Coll: ${getSampleCollectionTimestampForLabelDisplay(
//                   content.sampleCollectionDateAndTimezone
//                 )}</Text>
//                 <FontInfo>
//                   <FontName>Courier New</FontName>
//                   <FontSize>7</FontSize>
//                   <IsBold>True</IsBold>
//                   <IsItalic>False</IsItalic>
//                   <IsUnderline>False</IsUnderline>
//                   <FontBrush>
//                     <SolidColorBrush>
//                       <Color A="1" R="0" G="0" B="0"></Color>
//                     </SolidColorBrush>
//                   </FontBrush>
//                 </FontInfo>
//               </TextSpan>
//             </LineTextSpan>
//           </FormattedText>
//           <ObjectLayout>
//             <DYMOPoint>
//               <X>1.1249999</X>
//               <Y>0.43043762</Y>
//             </DYMOPoint>
//             <Size>
//               <Width>1.085</Width>
//               <Height>0.13704132</Height>
//             </Size>
//           </ObjectLayout>
//         </TextObject>
//         <TextObject>
//           <Name>Account</Name>
//           <Brushes>
//             <BackgroundBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BackgroundBrush>
//             <BorderBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BorderBrush>
//             <StrokeBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </StrokeBrush>
//             <FillBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </FillBrush>
//           </Brushes>
//           <Rotation>Rotation0</Rotation>
//           <OutlineThickness>1</OutlineThickness>
//           <IsOutlined>False</IsOutlined>
//           <BorderStyle>SolidLine</BorderStyle>
//           <Margin>
//             <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
//           </Margin>
//           <HorizontalAlignment>Left</HorizontalAlignment>
//           <VerticalAlignment>Middle</VerticalAlignment>
//           <FitMode>None</FitMode>
//           <IsVertical>False</IsVertical>
//           <FormattedText>
//             <FitMode>None</FitMode>
//             <HorizontalAlignment>Left</HorizontalAlignment>
//             <VerticalAlignment>Middle</VerticalAlignment>
//             <IsVertical>False</IsVertical>
//             <LineTextSpan>
//               <TextSpan>
//                 <Text>Acct #: ${content.accountNumber}</Text>
//                 <FontInfo>
//                   <FontName>Courier New</FontName>
//                   <FontSize>7</FontSize>
//                   <IsBold>True</IsBold>
//                   <IsItalic>False</IsItalic>
//                   <IsUnderline>False</IsUnderline>
//                   <FontBrush>
//                     <SolidColorBrush>
//                       <Color A="1" R="0" G="0" B="0"></Color>
//                     </SolidColorBrush>
//                   </FontBrush>
//                 </FontInfo>
//               </TextSpan>
//             </LineTextSpan>
//             <LineTextSpan />
//           </FormattedText>
//           <ObjectLayout>
//             <DYMOPoint>
//               <X>0.04000002</X>
//               <Y>0.56964654</Y>
//             </DYMOPoint>
//             <Size>
//               <Width>2.0579083</Width>
//               <Height>0.13794978</Height>
//             </Size>
//           </ObjectLayout>
//         </TextObject>
//         <TextObject>
//           <Name>Account and Order</Name>
//           <Brushes>
//             <BackgroundBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BackgroundBrush>
//             <BorderBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </BorderBrush>
//             <StrokeBrush>
//               <SolidColorBrush>
//                 <Color A="1" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </StrokeBrush>
//             <FillBrush>
//               <SolidColorBrush>
//                 <Color A="0" R="0" G="0" B="0"></Color>
//               </SolidColorBrush>
//             </FillBrush>
//           </Brushes>
//           <Rotation>Rotation0</Rotation>
//           <OutlineThickness>1</OutlineThickness>
//           <IsOutlined>False</IsOutlined>
//           <BorderStyle>SolidLine</BorderStyle>
//           <Margin>
//             <DYMOThickness Left="0" Top="0" Right="0" Bottom="0" />
//           </Margin>
//           <HorizontalAlignment>Left</HorizontalAlignment>
//           <VerticalAlignment>Middle</VerticalAlignment>
//           <FitMode>None</FitMode>
//           <IsVertical>False</IsVertical>
//           <FormattedText>
//             <FitMode>None</FitMode>
//             <HorizontalAlignment>Left</HorizontalAlignment>
//             <VerticalAlignment>Middle</VerticalAlignment>
//             <IsVertical>False</IsVertical>
//             <LineTextSpan>
//               <TextSpan>
//                 <Text>Order #: ${content.orderNumber}</Text>
//                 <FontInfo>
//                   <FontName>Courier New</FontName>
//                   <FontSize>7</FontSize>
//                   <IsBold>True</IsBold>
//                   <IsItalic>False</IsItalic>
//                   <IsUnderline>False</IsUnderline>
//                   <FontBrush>
//                     <SolidColorBrush>
//                       <Color A="1" R="0" G="0" B="0"></Color>
//                     </SolidColorBrush>
//                   </FontBrush>
//                 </FontInfo>
//               </TextSpan>
//             </LineTextSpan>
//           </FormattedText>
//           <ObjectLayout>
//             <DYMOPoint>
//               <X>0.040000014</X>
//               <Y>0.70885116</Y>
//             </DYMOPoint>
//             <Size>
//               <Width>2.1201644</Width>
//               <Height>0.13289689</Height>
//             </Size>
//           </ObjectLayout>
//         </TextObject>
//       </LabelObjects>
//     </DynamicLayoutManager>
//   </DYMOLabel>
//   <LabelApplication>Blank</LabelApplication>
//   <DataTable>
//     <Columns></Columns>
//     <Rows></Rows>
//   </DataTable>
// </DesktopLabel>`;
// };
