export const dataTestIds = {
  continueButton: 'loading-button',
  differentFamilyMember: 'Different family member',
  firstFlowPageTitle: 'first-flow-page-title',
  flowPageTitle: 'flow-page-title',
  startVirtualVisitButton: 'start-virtual-visit-button',
  startInPersonVisitButton: 'start-in-person-visit-button',
  scheduleVirtualVisitButton: 'schedule-virtual-visit-button',
  scheduleVirtualVisitStatesSelector: 'schedule-virtual-visit-states-selector',
  scheduleInPersonVisitButton: 'schedule-in-person-visit-button',
  firstAvailableTime: 'first-available-time',
  contactSupportButton: 'contact-support-button',
  navigatePastVisitsButton: 'navigate-past-visits-button',
  patientNameReviewScreen: 'patient-name-review-screen',
  locationNameReviewScreen: 'location-name-review-screen',
  prebookSlotReviewScreen: 'prebook-slot-review-screen',
  walkInSlotReviewScreen: 'walkin-slot-review-screen',
  privacyPolicyReviewScreen: 'privacy-policy-review-screen',
  termsAndConditionsReviewScreen: 'terms-conditions-review-screen',
  thankYouPageSelectedTimeBlock: 'thank-you-page-selected-time-block',
  backButton: 'control-back-button',
  editButtonReviewScreen: 'edit-button-review-screen',
  patientNamePaperworkReviewScreen: 'patient-name',
  locationNamePaperworkReviewScreen: 'location-name',
  checkInTimePaperworkReviewScreen: 'check-in-time',
  deletedButton: 'delete-button',
  fileCardClearButton: 'file-card-clear-button',
  fileCardUploadingButton: 'file-card-uploading-button',
  wrInviteeName: 'wr-invitee-name',
  wrInviteeContact: 'wr-invitee-contact',
  cardNumber: 'card-number',
  itemAddedValue: 'item-added-value',
  header: {
    authenticated: 'header-for-authenticated-user',
    unauthenticated: 'header-for-unauthenticated-user',
  },
};
