export const dataTestIds = {
  continueButton: 'loading-button',
  differentFamilyMember: 'Different family member',
  firstFlowPageTitle: 'first-flow-page-title',
  flowPageTitle: 'flow-page-title',
  startVirtualVisitButton: 'start-virtual-visit-button',
  startInPersonVisitButton: 'start-in-person-visit-button',
  scheduleVirtualVisitButton: 'schedule-virtual-visit-button',
  scheduleInPersonVisitButton: 'schedule-in-person-visit-button',
  firstAvailableTime: 'first-available-time',
  contactSupportButton: 'contact-support-button',
  navigatePastVisitsButton: 'navigate-past-visits-button',
  patientNameReviewScreen: 'patient-name-review-screen',
  locationNameReviewScreen: 'location-name-review-screen',
  prebookSlotReviewScreen: 'prebook-slot-review-screen',
  walkInSlotReviewScreen: 'walkin-slot-review-screen',
  privacyPolicyReviewScreen: 'privacy-policy-review-screen',
  termsAndConditionsReviewScreen: 'terms-conditions-review-screen',
};
