export const FEATURE_FLAGS = {
  LAB_ORDERS_ENABLED: import.meta.env.VITE_APP_IS_LAB_ORDERS_ENABLED_FEATURE_FLAG === 'true',
  RADIOLOGY_ENABLED: import.meta.env.VITE_APP_IS_RADIOLOGY_ENABLED_FEATURE_FLAG === 'true',
};
